### ISSUE TITLE
feature suggestion: mark date with exceptional events

### ISSUE THREAD

**Issue by aviv1620** [hasadna/open-bus-map-search#104]
Is it a good idea to make a feature that marks dates with exceptional events?

For example, if we look in 'gaps' when there is war and the bus can be gapped because of 'Red color alarm'.
Another example we look in 'gaps' when there is a demonstration and the bus can be gapped because the roads are blocked.

![Untitled](https://github.com/hasadna/open-bus-map-search/assets/44925669/3fbf4813-a5af-478b-9f39-c50b7e673847)

**Comment by ArkadiK94** [comment]
@aviv1620 I think it is a good idea, however, in moovit for example they mark only the effected routes. A special events not necessarily impact all the routes across the country. 

@NoamGaash @shootermv What do you think?

**Comment by NoamGaash** [comment]
I don't like the idea of maintaining such a list manually. I won't do that

**Comment by aviv1620** [comment]
I think we can close the issue.
We not have way to data scraping the exceptional events.

**Comment by NoamGaash** [comment]
@aviv1620 Thanks!
Anyway, there are some other problematic events that we should consider:
https://github.com/hasadna/open-bus-map-search/issues/24
Closing this issue for now, please let us know if anyone wants to re-open it.
