### ISSUE TITLE
ci: verify clean tree

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#106]
1. if running `yarn` will make changes to the `yarn.lock`, CI should fail
2. if we have a `package-lock.json` file in the root folder, CI should fail
3. if running `yarn run build` created things outside the `.gitignore`, CI should fail

for example:
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/22c9e88f-7795-4454-ab79-135b8e91310b)
https://github.com/microsoft/playwright/actions/runs/6464306848/job/17548743565?pr=27519

**Comment by ArkadiK94** [comment]
Pls, assign me, I would like to try it out. Honestly, for now, I don't know exactly how to do it but I want to research a solution.

**Comment by NoamGaash** [comment]
good luck! @ArkadiK94
feel free to copy from playwright
