### ISSUE TITLE
Add references to the repo and Hasadna in the UI

### ISSUE THREAD

**Issue by ShayAdler** [hasadna/open-bus-map-search#12]
Add the following data to the main screen (links for inspiration) -
- [ ] About - https://next.obudget.org/about/ (here we should add a short explanation about how the data is collected, which manipulations we do etc).
- [ ] Donate - https://www.jgive.com/new/he/ils/donation-targets/3268#donation-modal
- [ ] Report a bug - https://github.com/hasadna/open-bus-map-search/issues

**Comment by Mordechai1323** [comment]
Hi Shay😊, Is there the design in the figma(I didn't find it)?
Thanks!

**Comment by ShayAdler** [comment]
@Mordechai1323 
Yes, [here](https://www.figma.com/file/NL8EgYn28UPTaZOPPMafpP/Untitled?type=design&node-id=202-8864&mode=design&t=PDrnvjs9kNMIykt4-0),  but it is not quite similar to the current design, so feel free to share if you have any doubts :)
I'd make the "Hasadna" logo clickable, referring to the donation link.

Regarding the specific text under the "about", I'll make something and post it here soon

**Comment by ShayAdler** [comment]
**מהו אתר "דאטאבוס"?**
אתר דאטאבוס של [הסדנא לידע ציבורי](https://hasadna.org.il/) מציג נתונים על איכות ביצוע קווי התחבורה הציבורית בארץ. דאטאבוס מחבר למעשה בין מספר מקורות מידע ממשלתיים:

* מידע התכנון - GTFS - המפורסם כל יום ומכיל את פרטי הקווים, מיקומי התחנות, שעות המעבר בהן וכו'.
* מידע הביצוע - SIRI - על כל קו בישראל מוצמד GPS שמדווח את מיקום האוטובוס כל כמה רגעים.

גילינו טעות או מידע לא מעודכן, מה עושים?
מכיוון שכל המידע המוצג באתר מתבסס על מקורות המידע הרשמיים, מומלץ לפנות לגורם המפרסם לצורך בירור או תיקון הבעיה. צוות "דאטאבוס" ישמח לסייע לכם להבין מיהו הגורם הממשלתי שפרסם את הנתון או המידע שדורשים בירור או תיקון.

**פרטיות**
באתר מוטמע שירות [Google Analytics](https://marketingplatform.google.com/about/analytics/) לניתוח דפוסי השימוש ומיצוב האתר במנועי חיפוש. קוד זה חושף בפני מפעילי השירות מידע בנוגע להתנהגות המשתמשים. [קראו כאן](https://support.google.com/analytics/answer/6004245?hl=he) על מדיניות הפרטיות של השירות.

רשיון שימוש
כל המידע המוצג באתר מבוסס על נתונים המפורסמים במקורות המידע הממשלתיים. השימוש במידע כפוף ל[רישיון CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) של [Creative Commons](https://creativecommons.org/).

שאלות? תגובות? רעיונות?
📫 [צרו איתנו קשר](http://www.hasadna.org.il/%d7%a6%d7%95%d7%a8-%d7%a7%d7%a9%d7%a8/)
📫 <אייקון של סלאק>[דברו איתנו על זה בסלאק](https://join.slack.com/t/hasadna/shared_invite/zt-167h764cg-J18ZcY1odoitq978IyMMig)

מימון
מרבית הפיתוח של האתר בוצע בהתנדבות במסגרת הסדנא לידע ציבורי.

לאורך השנים, הפרויקט קיבל מימון נוסף גם מהגופים הבאים:

משרד ראש הממשלה
האיחוד האירופי
רשות החדשנות
חברת "מגדל"
ועוד מספר תורמים קטנים יותר.

**Comment by Mordechai1323** [comment]
Ok,could you please assign me to this task?
