### ISSUE TITLE
add loading animation to patterns page

### ISSUE THREAD

**Issue by Pafestivo** [hasadna/open-bus-map-search#125]
on the patterns page, when you choose a new bus route it takes about 4 seconds to fetch and show the data.
right now there is no indicator that the data is being fetched, i'd suggest adding some sort of spinner or loading indicator.

i can take this issue if needed :)

**Comment by NoamGaash** [comment]
Thank you! That's a great idea :clap: 
looking forward to see your contribution :crown: 
good luck!
