### ISSUE TITLE
ci: can be better to create separate yml file for lint job

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#127]
currently lint is one of jobs of playwright task
it can be better for `lint` to be on a separate file
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/e9aeac27-c02b-487d-9ae7-f598a4bd679e)

**Comment by griseduardo** [comment]
Hello, I would like to work in this issue

**Comment by griseduardo** [comment]
@NoamGaash @shootermv can you assign me this one?

**Comment by griseduardo** [comment]
Hello, I opened the pr here: https://github.com/hasadna/open-bus-map-search/pull/141

**Comment by NoamGaash** [comment]
this issue is fixed
