### ISSUE TITLE
new design suggestion for sidebar

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#132]
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/1701847b-d632-400b-8262-6a7975d791e6)

**Comment by shootermv** [comment]
what do you think?

**Comment by shootermv** [comment]
one more logo suggestion:
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/535943d4-33db-4d08-8593-22eccdd128e1)

**Comment by NoamGaash** [comment]
I love it, especially the icons. It feels way more informative.
However - let's wait for the others on slack to respond
