### ISSUE TITLE
duplicated bus stations at `stations list`

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#134]
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/dde077cf-24da-4c1e-aa24-abec62c14cb6)

reproduce steps
1. go to לוח זמנים הסטורי  page
2. select אגד תעבורה
3. select 364 line
4. select `היכל המשפט/אבא אבן-ירושלים ⟵ 'מיצד א-אספר`
5. try to select some station - you will see stations names are duplicate

**Comment by Pafestivo** [comment]
It happens on many lines, each entry presents you with different times, but I think it will be a good idea to merge those duplications to just one entry containing all the different times.

I believe it's worth doing on the backend, that will just return the data as we want it.
But if it's not possible you can assign the issue to me and I'll make a helper function to manipulate the data on the front end.

**Comment by shootermv** [comment]
totally agree that it better be done at backend...

**Comment by Pafestivo** [comment]
Okay, so let me know if I should work on it on the front or not 😄

@NoamGaash what do you think?

**Comment by shootermv** [comment]
Can you try to see if it possible fix it at the back?

**Comment by Pafestivo** [comment]
Okay, I'll take a look there and get back to you Sunday/Monday with my thoughts

**Comment by shootermv** [comment]
Thank you very much

**Comment by NoamGaash** [comment]
AFAIK, there are subtle differences between both variations
@ShayAdler wdyt?

**Comment by ShayAdler** [comment]
So from a very quick glance, this is not a real backend problem, but a problem with how we query the data.
If you take a look at the requests in the network tab, you'll see that we don't filter well on the dates, which results a duplication of rides, and therefore of stops:
* `https://open-bus-stride-api.hasadna.org.il/gtfs_routes/list?limit=100&date_from=2023-10-18&date_to=2023-10-19&operator_refs=4&route_short_name=364` -> returns 6 results (2 routes of each line ref). The reason for that is that think the gtfs data is generated per day (in the MOT servers, as well as in the backend, because the planned routes can change)
* Therefore 2 rides are queried (1 for the 18.10, one for the 19.10), and this is why we get the stops duplication:
<img width="346" alt="Screenshot 2023-10-19 at 12 15 12" src="https://github.com/hasadna/open-bus-map-search/assets/75563038/3fcf11c7-5822-4c71-90ac-8887c8e03d37">

**Comment by Pafestivo** [comment]
So given the new info, do we want to merge those entries? Or maybe add the dates to the names to make the difference clearer? [stopName] - [dateOfTheInfo]
```
היכל המשפט/אבא אבן-ירושלים ⟵ 'מיצד א-אספר - 18.10
היכל המשפט/אבא אבן-ירושלים ⟵ 'מיצד א-אספר - 19.10
```

**Comment by NoamGaash** [comment]
filter out results with the same ID sounds like a good idea
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/ac3a2779-767a-4b73-ae2a-564e217aa7fe)

**Comment by Pafestivo** [comment]
Awesome, I'll take a look over it ;)

**Comment by ShayAdler** [comment]
@NoamGaash  is there a reason not to query only the actual date the user filtered on? This will solve the issue..
This bigger range selection sounds buggy for another reason - what if I searched for the 18.10, and this route does not exsit in this date, but is does exist on the 19.10? Currently, I'll see it in the search results

**Comment by NoamGaash** [comment]
you're right, it will be a better solution

**Comment by Pafestivo** [comment]
Perfect, so I have my task.
I'll go over the code and get to it.
Will update you soon

**Comment by Pafestivo** [comment]
so i took a deeper look on that issue, and it doesn't seem related to the dates.
i logged what i got back from the server and saw this:
![image](https://github.com/hasadna/open-bus-map-search/assets/111818269/490276c0-e189-461c-8d7f-c646e1dcf7cf)
they are all the same dates, only difference is the route name(look at the last two characters of each duplications)
i can't really put my finger on why we get those duplications. will you be able to take a quick look?
here is the example of the data i tried to query on the frontend:
![image](https://github.com/hasadna/open-bus-map-search/assets/111818269/d598577e-9cfb-41df-9306-f757778cc61b)


waiting on your response <3 @NoamGaash @ShayAdler Thanks!

**Comment by ArkadiK94** [comment]
@NoamGaash I close this issue, the discussion about this issue continues in issue #176

**Comment by AdlerShay** [comment]
Hi, @ArkadiK94 you sure this is the same problem? My issue is trying to better handle a by-design case, while this is an actual big.

**Comment by ArkadiK94** [comment]
Yeah, @Pafestivo wrote that the difference between the routes is only the key one with # while the other with number. Which indicates that there are two routes with the same "from destination" and "to destination".  Maybe,  I am wrong tell me if so , and I will reopen this issue.

**Comment by ArkadiK94** [comment]
I am sorry, the issue talks about two different routes where here the bug is about duplicated stops. As a result,  I am not sure if it is the same issue so I will reopen it for now. @ShayAdler @AdlerShay

**Comment by ShayAdler** [comment]
@ArkadiK94 yep this is definitly confusing 😅 , but I still think this is not the same issue. The diff is that in #176 , the `line_ref` is different (in gtfs, each direction of the line gets a different `line_ref`, so for exmaple the same line 37 from Tel Aviv to Yehud does not have the same line ref as from Yehud to Tel Aviv, the same goes for "halufot").

Here are you can see, it is the same (as well as the `route_long_name` and `route_mkt`, but the dates are different.
I have not deeply investigated the pattern with the "#", but I guess that this line can sometimes have other halufot.
Let me know if it is still unclear :)

<img width="859" alt="image" src="https://github.com/hasadna/open-bus-map-search/assets/61648359/47cfda56-f8ea-4c0c-90ff-bc1eea542a1a">

**Comment by ArkadiK94** [comment]
@ShayAdler @NoamGaash Do you want this issue to be still open to make the relevant changes in the backend? Or is the filter in frontend is enough?

**Comment by NoamGaash** [comment]
@ArkadiK94 
I'm not sure, feel free to re-open

**Comment by ArkadiK94** [comment]
ok, I re-opened it for now, let's wait the response of @ShayAdler if there is required a change in the back-end as well

**Comment by ShayAdler** [comment]
@ArkadiK94 , looks great, I think you can close 🙏 😄
