### ISSUE TITLE
[Bug] Fix Layouts

### ISSUE THREAD

**Issue by ArkadiK94** [hasadna/open-bus-map-search#145]
Think open new issues.
PR  #54 destroy the layout.

And the place need to be here:
![Screenshot 2023-10-07 010101](https://github.com/hasadna/open-bus-map-search/assets/44925669/beede96e-e64d-4ad9-88cc-11c8844d1cd0)

_Originally posted by @aviv1620 in https://github.com/hasadna/open-bus-map-search/issues/80#issuecomment-1751448102_

We should fix the layouts of DashboardPage and GapsPatternsPage

DashboardPage:
Before:
![image](https://github.com/hasadna/open-bus-map-search/assets/76536506/1b444e19-61cc-4208-ad3e-647f4e229085)
![image](https://github.com/hasadna/open-bus-map-search/assets/76536506/1745777d-b551-43fa-a9b0-68b8dcf70e1e)

After:
![image](https://github.com/hasadna/open-bus-map-search/assets/76536506/71a2ebd7-2bf2-40de-9550-9296cd3e89b6)
![image](https://github.com/hasadna/open-bus-map-search/assets/76536506/bbe58dd2-0e86-429a-bcb6-777a6a674328)

GapsPatternsPage:
Before:
![image](https://github.com/hasadna/open-bus-map-search/assets/76536506/5ceeb3a8-33a2-4de1-8704-32abf6344468)

After:
![image](https://github.com/hasadna/open-bus-map-search/assets/76536506/a9ea1fb0-cb9a-4676-812b-d0c2ab59ba2f)

**Comment by ArkadiK94** [comment]
@NoamGaash , I close this issue, the pr was merged.

**Comment by NoamGaash** [comment]
thank you!it looks so much better :clap:
