### ISSUE TITLE
DashboardPage - style suggestion to the HbarChart

### ISSUE THREAD

**Issue by Nastia1409** [hasadna/open-bus-map-search#147]
![image](https://github.com/hasadna/open-bus-map-search/assets/22620219/ac74a1ad-ed40-4334-9c16-62ca7b7f0d74)
![image](https://github.com/hasadna/open-bus-map-search/assets/22620219/f3c5adc0-a8f8-49cc-b703-146bef85c3c1)

wdyt?
@NoamGaash 
#hacktoberfest

**Comment by NoamGaash** [comment]
that's so cool! Personally, I really like your design.
I'll ask the community on our Slack & Discord servers.
Do you speak Hebrew by any chance?
Thanks for your contribution

**Comment by Nastia1409** [comment]
מדברת עברית חופשי :)

**Comment by NoamGaash** [comment]
so feel free to join!
official channel - https://join.slack.com/t/hasadna/shared_invite/zt-21qipktl1-7yF4FYJVxAqXl0wE4DlMKQ
discord (FE only) - https://discord.gg/99xS4kQN

**Comment by shootermv** [comment]
ממש אוהב את העיצוב.
מה שעוד היתי משנה פה: הייתי לא מציג את הרישמה של כ30 ברים, אלא מציג רק 5. ולמטה היתי מוסיף כפתור "טען עוד"

**Comment by NoamGaash** [comment]
anyway, feel free to open a pull request :star:

**Comment by Nastia1409** [comment]
Great, can you assign me? under the hacktoberfest :)
