### ISSUE TITLE
Support investigation of misses patterns by hour and line

### ISSUE THREAD

**Issue by ShayAdler** [hasadna/open-bus-map-search#15]
**Use case**: Identifying of lack of execution by hour patterns

**Example**:
If we group by the execution metrics of line 64 of Electra Afikim from 1.7-30.7 by hour, we can easily identify patterns (take a look at 9:30):
![64_misses_july_by_Hour (1)](https://github.com/hasadna/open-bus-map-search/assets/61648359/0bdeaa00-7ae2-4e00-82d0-68021a99ca77)

**Suggestion**:
* In the "gaps" page, allow selecting a range of dates.
* When more than 1 day is selected, the results will be grouped -by hour, so instead of "V", "X", we'll see the following columns:
  * total planned
  * total executed
  * miss percentage - colored red-yellow-green.

**Comment by ArkadiK94** [comment]
@NoamGaash , I close this issue because I see that it was resolved and merged in Gaps patterns page #44 pr
