### ISSUE TITLE
add missing locale keys

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#156]
one of side menus displays some key instead of text
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/3342ec85-0cb6-4380-a2c1-0c5189880816)
`  "gaps_patterns_page_title": "דפוסי נסיעות שלא יצאו" ` needs to be added to `en.json` & `heb.json` locale files

**Comment by Virtual4087** [comment]
I'd like to work on it. Can you assign this to me?

**Comment by NoamGaash** [comment]
Hi, it solved last night,
@Virtual4087
However, refactoring will be nice. I think we should get rid of `TEST` and `TEXT_KEYS`
