### ISSUE TITLE
Add lint rules

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#160]
* make errors for unused imports and exports
* prevent circular dependencies

**Comment by giladfuchs** [comment]
@NoamGaash 


after run this command at src folder 
` npx madge --extensions js,ts --circular .
`
I got 
`✔ No circular dependency found!
`
so we are ok.

we can add it to the ci.


I added to eslint.json
"@typescript-eslint/no-unused-vars": "on",
and for tsconfig.json
    "noUnusedLocals": true,

I get error mostly of import React.

I can remove all  unused imports 

for unused export I can use 
ts-prune

let me know if you want me to do this and work on this issue!

**Comment by NoamGaash** [comment]
thank you
https://stackoverflow.com/questions/42541559/eslint-with-react-gives-no-unused-vars-errors
