### ISSUE TITLE
the input group-by-hour  better to moved to be above line charts card

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#168]
this filter input changes only the line charts area, but not the horizontal bars charts (where this input located currently )
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/0a3738df-b96c-4063-ad42-99df63e165bd)

here is some screenshot of how i think it could look:
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/3f3ef511-6a55-497e-ae95-50f62c1cfd29)

by hour
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/c72e1eee-e952-4fb8-9838-43fa9a91ff7d)

**Comment by TomRytt** [comment]
I'll gladly to take care of this today. I just need help with aligning the CSS to the other elements in the site please.
