### ISSUE TITLE
eslint rule

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#184]
I think this rule can benefit our repo
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unused-modules.md
I'm open to more idea regarding rules you find interesting.

**Comment by i5x64BIT** [comment]
@NoamGaash  We already have some solid linting, outdated issue?

**Comment by NoamGaash** [comment]
@i5x64BIT this specific rule isn't turned on
