### ISSUE TITLE
Lazy load pages

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#187]
Using dynamic imports

**Comment by KazemHe** [comment]
Done

**Comment by NoamGaash** [comment]
@KazemHe thanks for your contribution!
please review the diffs, the CI errors and the conflicts in your pr :pray:

**Comment by ArkadiK94** [comment]
Hmm, I think there are two people that work on this issue. Pr #188 #210 . @NoamGaash @KazemHe @shootermv . Moshe, if you have the permissions to make yourself assigned to an issue for next time pls do it 🙏

**Comment by ArkadiK94** [comment]
I assigned you both, up to you to decide which one will do it. You can collaborate,  if you want.

**Comment by NoamGaash** [comment]
please stop opening PRs. use the same PR, and force push if needed.

**Comment by NoamGaash** [comment]
Thanks @KazemHe ! Great work :clap:
