### ISSUE TITLE
Profile page for lines 

### ISSUE THREAD

**Issue by VSciFlight** [hasadna/open-bus-map-search#193]
As for what was suggested in the slack group.

The idea is to create a page that shows information about a specific bus line.

This page will contain basic information such as the route of the bus relative to a map, bus line number, operator company, line schedule.
The page will also contain specific bus drive information. This will have a 3 inputs to have the right line: Direction of the drive, Station, Date and Time. These inputs will output the relevant bus drive, its driver name, its timeline.

From that information we can also add a line graph that shows the time differentiation in reality related to the schedule and calculate the arrival difference. More information in the picture.
It is possible to make it even more advanced and show additional series to show the average of that bus drive station.

@ShayAdler suggested to use more features that are exists such as "מפה לפי קו", "נסיעות שלא יצאו" and also include the bus rating in the basic information.

Illustration:
![Untitled Diagram drawio](https://github.com/hasadna/open-bus-map-search/assets/119410516/2dad90c0-fd4d-4a0e-8001-232e140c47c6)

**Comment by xoRmalka** [comment]
Did you start to work on it?

@VSciFlight

**Comment by VSciFlight** [comment]
@xoRmalka 

Yep, but I have some difficulties

**Comment by xoRmalka** [comment]
@VSciFlight 

Do you want to collaborate with me? We can look at it together :)

**Comment by VSciFlight** [comment]
@xoRmalka I would love to :)

**Comment by ArkadiK94** [comment]
I reopened this issue because this is still in progress as was mentioned in the pr.

**Comment by NoamGaash** [comment]
I'm closing this issue, and open small sub-tasks instead
