### ISSUE TITLE
create CONTRIBUTION.md file

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#194]
I believe it should include:

- Links to the video tutorials on my youtube channel https://www.youtube.com/watch?v=6H6jkJCVhgk&t=4s&pp=ygUKbm9hbSBnYWFzaA%3D%3D https://www.youtube.com/watch?v=jEWG7nYKk_0&t=137s https://www.youtube.com/watch?v=DWp4cwd97TI
- Explanation about linting and testing
- links to discord and slack
- anything else comes up on your mind

**Comment by Tashuuuu** [comment]
I would like to work on it

**Comment by NoamGaash** [comment]
Cool, thanks!

**Comment by ArkadiK94** [comment]
[ ] Explanation about ci and the need to check it's status.

**Comment by ArkadiK94** [comment]
Hi, @Tashuuuu  are you working on this issue? If you have any questions you are welcome to ask.
