### ISSUE TITLE
Docs | Create a PR to list us on awesome-opensource-israel

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#195]
https://github.com/lirantal/awesome-opensource-israel/edit/master/README.md#react

**Comment by Roni750** [comment]
I'll gladly incorporate open-bus repo in the awesome-opensource-israel list :)
Should I add it in the "react" section of the list?

**Comment by NoamGaash** [comment]
@Roni750 Yes, thank you! That would be awesome 👌👏

**Comment by Roni750** [comment]
@NoamGaash PR confirmed & merged into the awesome-opensource-israel/master 😎

**Comment by NoamGaash** [comment]
Amazing! thank you @Roni750 :clap:
