### ISSUE TITLE
get rid of yarn 1.x

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#199]
I made a PR, but I would like some help with it.
https://github.com/hasadna/open-bus-map-search/pull/197
options:

1. We can upgrade yarn version - but seems like Netlify doesn't like it. Please help me figure out why, as I don't have the capacity.
2. we can get rid of yarn completely and use NPM instead

Thanks everyone, I'm so glad that we have this community

**Comment by shootermv** [comment]
Or pnpm
