### ISSUE TITLE
Remove unsupported operators from the "by time" widget

### ISSUE THREAD

**Issue by ShayAdler** [hasadna/open-bus-map-search#20]
The same operators that were removed from the "by operator" widget should be hidden here as well - 
https://github.com/hasadna/open-bus-map-search/blob/5ca51cc165d9cd43397c5161200615f9d693ceb6/src/pages/dashboard/OperatorHbarChart/OperatorHbarChart.tsx#L17

**Comment by shlev** [comment]
fixed , sent pull request.

**Comment by ShayAdler** [comment]
@NoamGaash As I see in the website this seems resolved, should we close?

**Comment by NoamGaash** [comment]
@ShayAdler you're right, thanks!
