### ISSUE TITLE
remove annoying console.log statements in the code 

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#200]
when you open chrome dev tool (or firefox dev tool or edge) you can see a lot of console stuff
which is better not to be there
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/9dacbb99-463d-41f4-9968-ff1ea2847651)

**Comment by codeomi** [comment]
having trouble pushing the code
`remote: Permission to hasadna/open-bus-map-search.git denied to omkarFintaar.`

**Comment by Abhid1239** [comment]
Hey, @shootermv can you please review my PR and approve it.

**Comment by shootermv** [comment]
hi @Abhid1239 !
glad to see you in our project!
For create a PR, you need:
1. create a fork (by pressing `fork` button at github repo)
2. clone a project on your machine (`git clone https://github.com/hasadna/open-bus-map-search`)
3. connect you local project to remote repo (`git remote set-url origin https://github.com/YOUR-NICKNAME/open-bus-map-search`)
4. create a branch with your changes 
only then you will be able to create a PR
please read contribution section (or some `[how to contribute to open source](https://medium.com/@moshevilner/useful-git-tips-when-making-your-first-contribution-or-importance-to-know-rebase-command-ac696c807b24)` guide)

**Comment by Abhid1239** [comment]
Hey @shootermv thanks for the detailed info.

Have created the the branch first and then created the PR please check

**Comment by NoamGaash** [comment]
thanks @Abhid1239 ! :clap:
