### ISSUE TITLE
it can be good to add somewhere a link to github repo of the site 

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#205]
i think it can be good to add a link to a  github repo (may be at header?)
as other many opensource sites
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/49d54ad4-35eb-4453-8cd7-b5d500284f44)

**Comment by xoRmalka** [comment]
Can you assign this to me?

**Comment by xoRmalka** [comment]
I think if we want an end user to refer us to a bug then it should be user-friendly and have some kind of bug-reporting form.

And then it makes sense to add the GitHub icon.

nonetheless, I have already done that:

![image](https://github.com/hasadna/open-bus-map-search/assets/107395990/6ea3661e-9cda-40d6-bb80-2cd68ccc4814)

![image](https://github.com/hasadna/open-bus-map-search/assets/107395990/c3d0f148-bad5-4435-9bc4-b0a5e2a03e9b)

**Comment by ArkadiK94** [comment]
> I think if we want an end user to refer us to a bug then it should be user-friendly and have some kind of bug-reporting form.

I agree with you about it, maybe we should open a new issue about it.

**Comment by ArkadiK94** [comment]
@xoRmalka @NoamGaash I see that the related pr was merged so I close this issue.
