### ISSUE TITLE
better inputs design

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#21]
https://www.figma.com/file/Plw8Uuu6U96CcX5tJyRMoW/Public-Transportation-visual-informaiton?type=design&node-id=0-1&mode=design&t=Dh8lI3EJ37unxvoe-0
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/6d75e8ad-b1a9-4495-843b-c5a9ef5c8278)

**Comment by aviv1620** [comment]
Assign

**Comment by aviv1620** [comment]
I use React Material UI for the inputs.
look better.
![Screenshot 2023-09-06 172301](https://github.com/hasadna/open-bus-map-search/assets/44925669/0d19fad3-f39c-4500-91f5-97365f00958f)
