### ISSUE TITLE
Move secrets to production deployments

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#222]
We want to let anyone run the CI workflows without waiting for maintainer permission.
The problem - one can use malicious workflow to steal the secrets.
By moving the secrets to environment scope, we can limit their scope to the `main` branch that's well protected
https://github.com/hasadna/open-bus-map-search/settings/environments/1670036998/edit

**Comment by OriHoch** [comment]
I added HASADNA_K8S_DEPLOY_KEY secret to production environment, you can remove it once you merge the PR

the AWS secrets are not relevant I think, anyway, I don't have them, you added them

**Comment by NoamGaash** [comment]
thanks!
