### ISSUE TITLE
Bug report form

### ISSUE THREAD

**Issue by xoRmalka** [hasadna/open-bus-map-search#224]
It is imperative to have a user-friendly bug-reporting form in place, rather than redirecting users to GitHub, if we want a seamless and efficient process for bug reporting.

We need to think about how we want the workflow of it to be.

**Comment by ArkadiK94** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue
There are many ways to create an issue in GitHub . In my opinion , this should be a regular form and the issue creation will happen automatically.

**Comment by xoRmalka** [comment]
I am thinking how it would be correct to do this, the end user is not a developer.

A complaint will arrive> and we will have to characterize it> and only then open an issue.

That is, there is a step in the middle that needs to be done.

I thought maybe we could build a form that has a structure for the questions that must be filled in and only then the issue will open.  

@ArkadiK94

**Comment by ArkadiK94** [comment]
It is a good idea, in addition,  the user will have to add a screen shot or short video. It will help in case the description will not be enough.

**Comment by xoRmalka** [comment]
I already created the page :)
(with the i18n)

![image](https://github.com/hasadna/open-bus-map-search/assets/107395990/3f711aef-7e01-4942-be5a-87adab5cc75d)

Now I want to send the data to the repo to create the issue, @ArkadiK94 - the docs link that you sent refers to GitHub users, look [here](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue) there is a REST API to Github that we can work with, but I need to create a token for this.

@NoamGaash, can you check about the token? 

I will also create the request to send to our backend and only from there the issue be sent, I want to do this due to security reasons, I don't want the token to be exposed on the front end.

**Comment by NoamGaash** [comment]
The Token can't be used from frontend context (security reasons), so creating an backend or a lambda will be required

**Comment by ShayAdler** [comment]
@xoRmalka good idea! maybe also adding some contact info of the user (optionally) can be helpful.
@NoamGaash wdyt about opening a route for that in stride-api instead of a dedicated be?

**Comment by NoamGaash** [comment]
@ShayAdler I was under the impression we want the stride API to have the single responsibility of providing the data. Shouldn't we use a different service?

**Comment by xoRmalka** [comment]
@ShayAdler @NoamGaash 

I added some contact info and styled the form :)

![image](https://github.com/hasadna/open-bus-map-search/assets/107395990/bea330e1-9485-4334-9775-8292ac5af9bf)

Now I'm working on the connection with the GitHub API.

**Comment by NoamGaash** [comment]
please make small pull requests rather then one commit with everything

**Comment by NoamGaash** [comment]
@xoRmalka  Hi, how is it going? Do you have any question? Let us know if any help is needed

**Comment by xoRmalka** [comment]
> @xoRmalka Hi, how is it going? Do you have any questions? Let us know if any help is needed

We need to get the server side live, I'd like to arrange a meeting and do it together, I estimate it will take us half an hour of work.
@OriHoch @NoamGaash

**Comment by xoRmalka** [comment]
Backend Is in the Air!
