### ISSUE TITLE
Create New Labels

### ISSUE THREAD

**Issue by ArkadiK94** [hasadna/open-bus-map-search#249]
In this repo, we use issues that related to different fields of development as front-end , back-end, data analysis and so on.
In my opinion, we should create a costume labels to indicate which issue related to each field and label the issues.
It will help developers to find the right issue for them easier. 
* if we will do it, we should add a section about it in the readme file.

@NoamGaash @ShayAdler What do you think?

**Comment by ArkadiK94** [comment]
https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#creating-a-label

**Comment by NoamGaash** [comment]
Feel free to do so - you're a maintainer

**Comment by ArkadiK94** [comment]
@ShayAdler In my opinion, the easier way is to change this repo name for "open-bus" and the repo that you linked to "open-bus-archive". Also, add in the README of this project a link to the other repo so we could check unresolved issues that are still relevant.

**Comment by NoamGaash** [comment]
@ShayAdler @ArkadiK94 we can keep the backend tasks there, and frontend tasks here.
this repo has no backend code at all
