### ISSUE TITLE
Unify all the timestamp in the system to Israel standard time

### ISSUE THREAD

**Issue by ShayAdler** [hasadna/open-bus-map-search#25]
In stride-api, timestamps are returned in utc 0 . Some of the pages in the UI convert it and some are not. 
The ones I found (buy please go over the pages are verify me :) ):
* "By operator widget" when grouped by hour
* timeline page

**Comment by giladfuchs** [comment]
since this map is relevant only for isreal.

i think more correct it's to do this on server side.

**Comment by NoamGaash** [comment]
@giladfuchs The server side should format the date.
The backend should return standard timestamp (ISO formatted, or epoch timestamp), and the frontend should format it.

**Comment by NoamGaash** [comment]
@giladfuchs in react we store the dates inside date / moment.js objects. therefore, making the backend change formats is meaningless. we ignore the backend formatting.

**Comment by i5x64BIT** [comment]
I can take it

**Comment by NoamGaash** [comment]
@i5x64BIT  Hi, how is it going? Do you have any question? Let us know if any help is needed

**Comment by i5x64BIT** [comment]
https://github.com/hasadna/open-bus-map-search/assets/62185136/7dfb7edc-25e4-4b49-a9a8-39074a214304

Done, does it look good?
Plus a few suggestion:
1. On the by-date there is duplicate information so either remove the indexes from x axis or remove the date from the display.
2. The by-hour graph is very confusing when it contains a few days, a simple solution would be to make a divider for each day and add a date index for each one, or give every second day a darker background.

Do I need to make a different pull request for the extra stuff?

**Comment by NoamGaash** [comment]
@i5x64BIT making separated pull request is recommended 
https://blog.codacy.com/small-pull-requests
