### ISSUE TITLE
[Fix] Mobile Support for Map Segment

### ISSUE THREAD

**Issue by ArkadiK94** [hasadna/open-bus-map-search#252]
In pages where we have a map segment make some adaptable for mobile change
An option:
We should add a button "view on map" when the user click it, will open a modal window with the map/redirect to map page. In this way, the map will be over all the screen and not a small window.
<img src="https://github.com/hasadna/open-bus-map-search/assets/76536506/d0a56f55-48e5-4e02-91af-7f7dd987dafe" width="200" height="400" />

_Originally posted by @ArkadiK94 in https://github.com/hasadna/open-bus-map-search/issues/16#issuecomment-1828052724_

If you have other suggestion for adaptation you welcome :)

**Comment by Roni750** [comment]
Hey, I'll gladly work on it 😎
Can you assign me please?

**Comment by Roni750** [comment]
@NoamGaash @ArkadiK94 
Hey mates, I implemented the styling for the expanded map (obviously the button isn't styled yet):

![image](https://github.com/hasadna/open-bus-map-search/assets/104915367/cd216cd7-8626-4eb0-8903-6997fdc07a12)

Now I'd like to work on the button styling, but when I went to search for which icons library we're working with, I saw none on package.json..
Should I work with mui-icons? I saw the other issue were you guys discussed which library should we work with.

**Comment by ArkadiK94** [comment]
@ant-design/icons , the library that we use for icons

**Comment by NoamGaash** [comment]
consider splitting it to two separate pull requests:
* the delivery will be faster
* the CR will be better (in terms of speed and quality)

**Comment by Roni750** [comment]
> consider splitting it to two separate pull requests:
> 
> * the delivery will be faster
> * the CR will be better (in terms of speed and quality)

Actually I've already incorporated styling as well using antd & antd/icons..
I'll make a PR shortly.

**Comment by Roni750** [comment]
@NoamGaash I think I took care of all your notes, apologies in advance if the revert on yarn.lock didn't succeed (I'm kinda new to advanced GitHub stuff), let me know if anything else needs to be done on my side :)
And thanks again for your kindness!

**Comment by NoamGaash** [comment]
would you like to try yourself reverting and solving the conflicts?

**Comment by Roni750** [comment]
> you're welcome, thanks! would you like to try yourself reverting and solving the conflicts? or I'll do it

Hey champ, sorry I really did try to revert the commit but I have no clue how to resolve the conflict with yarn.lock and I don't want to screw things up around here.
Hopefully in my future contributions I'll already know better how to use GitHub in a vast environment (I'm really used to develop alone)

**Comment by NoamGaash** [comment]
```
git checkout main yarn.lock
git add yarn.lock
git commit -m "chore: reset yarn.lock to main"
git pull origin main
git push
```
done

**Comment by Roni750** [comment]
@NoamGaash I just made a commit without the media query for mobile devices. Now we can have the expand button on all devices :)
Should I make a new PR?

**Comment by NoamGaash** [comment]
sure! I'd love that. thank
