### ISSUE TITLE
Collapsible menu(at dashboard page) - make the collapse animation faster

### ISSUE THREAD

**Issue by xoRmalka** [hasadna/open-bus-map-search#254]
@xoRmalka @shootermv it's already merge, so feel pree to open issue or another PR if needed

_Originally posted by @NoamGaash in https://github.com/hasadna/open-bus-map-search/issues/215#issuecomment-1817497101_

**Comment by NoamGaash** [comment]
Hi @xoRmalka , thanks for opening this issue.
some ideas to make it easier for newcomers:
* add a screenshot
* describe the intended behaviour rather the observed one (i.e "make the collapse animation faster")
good luck :stars:

**Comment by shootermv** [comment]
one thing i can assume as cause of slowness -
the resize of chart`s container which occurs when menu collapses -
makes the charts rerender multiple times (to adapt themselves to the width of container)

may be if we can handle the collapse animation start, and replace charts by `skeletons`  during the collapsing animation - it will make the situation better?
so far is my idea

**Comment by xoRmalka** [comment]
I found a solution. I'm updating the PR. 🚀
