### ISSUE TITLE
dashboard page logic can be split to subcomponents 

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#258]
this page has 3 chart areas and chart filters
currently there is a lot of logic here...
lot of states each one of them belongs to different chart:
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/ffa17944-5a6d-4362-b5b8-cbb5a155007f)
i think -
we can move the logic to 3 separate components, and make dashboard page code look like here:
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/f4081426-236d-41b3-94c6-22f9bb28f6ce)

**Comment by TomRytt** [comment]
I started working on it, can you please assign it to me?

**Comment by shootermv** [comment]
unfortunately , i disabled this, by mistake
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/460f218d-2b0d-47b6-8f48-5622896fc601)
my bad, will fix it

**Comment by shootermv** [comment]
actually i had a plan - to make each chart to have its own filters (that will affect only specific chart), but i guess it is something that need to be discussed at slack
