### ISSUE TITLE
Create a secret route /data-research

### ISSUE THREAD

**Issue by ShayAdler** [hasadna/open-bus-map-search#261]
Just a route that everyone who adds feature in the MS can use, that will not be exposed in the UI.

**Comment by NoamGaash** [comment]
tasks (can be done on different PRs):

- [ ] create an empty page in the specified path
- [ ] create an easter egg to open that path
- [ ] place some nice GIF/emoji to tell everyone it's under development

**Comment by ArkadiK94** [comment]
To clarify, need to create a new URL route not a bus route.

**Comment by Haim-S** [comment]
I created a protected path, I hope you liked it (:

**Comment by NoamGaash** [comment]
@Haim-S thanks for your contribution!
The term `protected` that we used was misleading, there is no authentication mechanism. Just don't link to that new rout
