### ISSUE TITLE
[Bug] Sort Hours in Gaps Page

### ISSUE THREAD

**Issue by ArkadiK94** [hasadna/open-bus-map-search#265]
In Gaps Page the "נסיעה שלא תוכננה" not displayed in sorted way. All this rides are at the bottom.

https://github.com/hasadna/open-bus-map-search/assets/76536506/891769e1-964b-4b5c-84b5-5d7d9c4f7633

**Comment by SergeyArenzon** [comment]
Can I be assigned to this issue?
