### ISSUE TITLE
[Bug] Cancel Fetch/Axios Requests

### ISSUE THREAD

**Issue by ArkadiK94** [hasadna/open-bus-map-search#268]
There is a problem when we send a request and than click on the clear button, it clears the data but because the request still in progress when it will finish the data will still display.

https://github.com/hasadna/open-bus-map-search/assets/76536506/e31f8cf7-0228-47c9-8475-029b44bf9d6f

**Comment by eyalyehia** [comment]
assign me!

**Comment by eyalyehia** [comment]
בטעות לחצתי unassigned העלתי את הPR שלו עכשיו
