### ISSUE TITLE
Edit CSS rules in About page 

### ISSUE THREAD

**Issue by amabelleS** [hasadna/open-bus-map-search#270]
Path: src>pages>About.tsx

<img width="408" alt="image" src="https://github.com/hasadna/open-bus-map-search/assets/45571546/6e1b855e-19a0-4294-adea-586a8d845d76">

In the Funding component (line 108), we need to change/add css rules, so that the <p> and rhe <a> will render in the same line.

Open API דאטאבוס פותח בסדנא לידע ציבורי, בעבודת מתנדבים, ומבוסס על

**Comment by NoamGaash** [comment]
@yardenmezi thanks!
