### ISSUE TITLE
[Bug] Map showing only the first line that was chosen

### ISSUE THREAD

**Issue by yardenmezi** [hasadna/open-bus-map-search#292]
When choosing one line after the other, the map still shows the first line
Scenario Recreation:
1. Open the single line page "מפה לפי קו"
2. Choose a line and watch it on the map
3. Clear the old line and choose a different line
4. Watch it on the map

https://github.com/hasadna/open-bus-map-search/assets/58609921/ddfc268c-fa75-4ef2-8c69-c0b2911b7289

**Comment by NoamGaash** [comment]
that's a hard one - not recommended for first time contributors.
the `useVehicleLocations` has a terrible implementation (my fault). 
Right now, it has a cache of vehicle locations by time. querying the same time = getting the same locations.
This bug can be solved by adding the line ref (if exists) to the key of the cache.
Anyway, we should consider replacing it / refactoring it / fixing it

**Comment by giladfuchs** [comment]
after playing with it 
I added @NoamGaash bug solution.

this part is tough to debug and renders a lot of time.
And it's a good idea to do their general refactor!

**Comment by NoamGaash** [comment]
@giladfuchs  :clap:   :clap:   :clap: 
<img src="https://media4.giphy.com/media/3XR0chfiSTtAI/giphy.gif"/>
