### ISSUE TITLE
Automation testing Infra creation

### ISSUE THREAD

**Issue by DanLeshinsky** [hasadna/open-bus-map-search#297]
Automation testing Infra creation:

1. Create test_pages folder which intended for automation test pages. 
2. Create BasePage.ts file under test_pages with reusable functions.
3. Create test_helpers folder intended for test data

**Comment by NoamGaash** [comment]
I'm not sure it will make the code more readable, maintainable or accessible for new contributors

**Comment by DanLeshinsky** [comment]
Hey Noam, good that you asked me that!

In my opinion the opposite is true. 
All automation environments require to follow working this way. 
This is also the right way to introduce junior’s who are interested in the automation field to show them how it should work if they of course want to enter the field through the project.
For example you shouldn’t see all these locators with it's bombastic xpathes or whatever in the spec level, it should be defined only in one place related to concrete application page, because only this page use it and it should be private. Just give it meaningful name and access through some getters or functions. 
Just imagine once your locator was changed by developer and this happens a lot in companies, you’ll have to change the same locator in all the tests. Of course it’ll not affect much when you have few tests only. 
In spec level you should see the flow in bullets like a running test and all the data should be hidden inside the test_helpers or test_data. 
Different pages are using almost the same functionality like click, fill text into some element, validate url page, select something from dropbox, thus it’s necessary to create some base class that all these application pages will inherit from it. And after that when you’ll be needed to add some logs or reports for such an actions you will change it only once in the base class.

You tell me if this is more readable:

  await page.getByRole('progressbar').waitFor({ state: 'hidden' })
  await page.getByLabel('בחירת תאריך').click()
  await page.getByRole('gridcell', { name: '1', exact: true }).click()
  await page.getByLabel('דקות').fill('6')

then this one?

        await timelinePage.selectOperatorFromDropbox("אגד");
        await timelinePage.fillLineNumber("1");
        await timelinePage.closeLineNumber();
        await timelinePage.verifyRouteSelectionVisible(false)

The code is singing by itself :-)

**Comment by NoamGaash** [comment]
Well, we don't use xpath based selectors.
While POMs are very common as an abstraction layer between the DOM structure and the test logic, I believe that it's good for bigger test suits. we barely have one test per page (and some pages have no tests at all), and the syntax we're using is the area-based selectors generated by Playwright's codegen. They are both readable and reflect the element's role.
