### ISSUE TITLE
Block selection of end date earlier from start date 

### ISSUE THREAD

**Issue by yardenmezi** [hasadna/open-bus-map-search#309]
In pages that have date range selection, the End date shouldn't allowed to be before the start date.
The current pages are dashboard and gaps_patterns.

**Comment by amabelleS** [comment]
I'll assign it to me:)

Should I tag the commits as a refactor or fix?

**Comment by amabelleS** [comment]
Maybe we also want to show an error message or alert the user that he/she entered an end date before the start date? 
I think this will be ok: 
<img width="569" alt="image" src="https://github.com/hasadna/open-bus-map-search/assets/45571546/79948064-cb66-414c-9c5e-7248fc0b84a9">

I also added it to the translations module: 
"bug_date_alert": "נא וודא שתאריך הסיום מאוחר יותר מתהאריך ההתחלה",

**Comment by amabelleS** [comment]
I think this issue was fixed. I made a PR for it some time ago...
Is there still some issue with the dates? Or can we close this one?

@NoamGaash @shootermv

**Comment by NoamGaash** [comment]
not needed - if it's fixed, let's close that issue. thanks!

**Comment by NoamGaash** [comment]
Wait - it's not blocked. It only gives a warning.
This issue is still relevant
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/29e689a1-69e1-4e04-be80-1168d254ea88)

**Comment by i5x64BIT** [comment]
@amabelleS 
היי, זה בדיוק מה שאני עשיתי, יש בחירה מהסוג הזה בדף הראשי ובדפוסי נסיעות.
חשבתי שאת כבר לא עובדת על האישיו הזה אז יש לי כבר pr מוכן. אם תרצי להמשיך לעבוד עליו אני יכול לשלוח אליך את השינויים שעשיתי :)
באופן כללי לדעתי הפתרון הכי טוב זה לפתוח קומפוננטה חדשה שתכלול 2 DatePickers שתקרא DateRangePicker (כמו בגרסאת הפרו)

**Comment by amabelleS** [comment]
@i5x64BIT 
מה מס' ה-PR שפתחת עליו? האמת כתבתי את ההודעה כמה דק לפני שפתחתי עליו PR. #521 
ממליצה לכתוב פה הודעה אם אתה עובד על אישיו, ככה לא יהיו כפילויות ועבודה סתם.. יהיה אפשר לשייך אותו אליך. 

לא יודעת מה עדיף, שני datePickers או אחד. לא הבנתי למה שניים.. כרגע היינו צריכים לממש min אז הוספתי לקיים, אבל כפרופ אופציונאלי. אפשר להוסיף גם maxDate כפרופ' אופציונאלי, השאלה אם יש בכך צורך כרגע. @NoamGaash ?

**Comment by i5x64BIT** [comment]
@amabelleS 

[2 DatePicker יחד](https://mui.com/x/react-date-pickers/date-range-picker/)
אפשר גם להוסיף לו עוד לוגיקה במידה הצורך.
הבעיה עם הפתרון של minTime maxTime זה הבילבול

**Comment by NoamGaash** [comment]
קומפוננטה לrange נשמע רעיון מעולה.
אם תרצו אפשר לעשות סקר קוד זה לזה, שנכניס גרסה משותפת :)

**Comment by i5x64BIT** [comment]
> קומפוננטה לrange נשמע רעיון מעולה.
> אם תרצו אפשר לעשות סקר קוד זה לזה, שנכניס גרסה משותפת :)

@NoamGaash האמת שאין לי מושג מה זה

**Comment by NoamGaash** [comment]
code review - https://github.com/features/code-review
בשביל להכניס לכאן קוד, לא צריך אישור שלי - מספיק שמישהו עושה PR ומישהו נוסף מאשר לו, והטסטים עוברים, ואפשר למזג
