### ISSUE TITLE
Stack bar (research graph) usability improvements

### ISSUE THREAD

**Issue by ShayAdler** [hasadna/open-bus-map-search#310]
Continuing this issue - https://github.com/hasadna/open-bus-map-search/issues/262, @ArkadiK94 suggested adding operators filtering, and I agree:
* Add an option to filter only specific operators. This will really help filtering out noise from small operators and can help the research.
* The filter should apply to all the graphs under this section ("בעיות etl/gps/משהו גלובאלי אחר")

Generally, I care less about visuality in this internal page, and more on the usability

**Comment by AssafGolani** [comment]
small note for new developers in this project: the path is /data-research
