### ISSUE TITLE
stride-api: fix timestamp example in docs

### ISSUE THREAD

**Issue by ShayAdler** [hasadna/open-bus-map-search#313]
oopsy, we have misleading docs, as described here https://github.com/hasadna/open-bus-stride-api/issues/13 
example: https://open-bus-stride-api.hasadna.org.il/docs#/gtfs/list__gtfs_ride_stops_list_get
but probably everywhere..

Change this to an example that can easily be copy-pasted and work out of the box.

**Comment by shootermv** [comment]
as far as i understand - the required change is at [stride-api](https://github.com/hasadna/open-bus-stride-api) repo
am i right?

**Comment by Senior-ai** [comment]
https://github.com/hasadna/open-bus-stride-api/issues/13 Solved. Unless there is another documentation with a different source 🤨

**Comment by ShayAdler** [comment]
@Senior-ai Thanks for the donation!
