### ISSUE TITLE
profile page - add a map of the planned route

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#316]
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/721378df-854d-4a2a-87e8-20c1a2fbbb05)
1. get the last ride of the route
2. get the stops of that the last ride (https://open-bus-stride-api.hasadna.org.il/docs#/gtfs/list__gtfs_ride_stops_list_get)
3. show the stops on a map

**Comment by NoamGaash** [comment]
see #193 for more ideas

**Comment by Senior-ai** [comment]
Got confused from #193 but i think I got the idea of this feature.
From the photo you have provided it seems like we also need to fetch the scheduled first and last ride of each day for the upcoming week. 
Regarding the most recent ride (I think that's what you meant, correct me if I'm wrong) by user's inputs - we can use mapbox and display each station with its long and lat and just connect a line between them, Should be easy using mapbox or OSM. let me know if I understood correctly - if so I don't mind to start working on it however I think I might need some help later on

**Comment by NoamGaash** [comment]
I don't really care about the table, this issue is more about adding a map of the line
like the one in Moovit
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/a0e4190a-8e31-410e-ad60-58ea4dfaec9f)

**Comment by Senior-ai** [comment]
Alright if its only displaying an OSM with our data I don't mind taking this issue. by the way I can see there are realtimeMap and singleLineMap which are not used at all as far as I know - were they created for this issue?

**Comment by NoamGaash** [comment]
@Senior-ai 
that's right.
Personally, I prefer re-using the same components from the singleLineMap page.
Note that the data is different - this task is about showing static (gtfs) data, related to the plan (תכנון נסיעה) rather than the Dynamic realtime SIRI information (דיווחי זמן אמת) we gathered when the bus executed the actual ride

**Comment by amabelleS** [comment]
How can I help to promote this issue? what help is needed?

**Comment by NoamGaash** [comment]
@amabelleS you can have this issue. do you have any question?

**Comment by NoamGaash** [comment]
@amabelleS seems like someone is on it
https://github.com/hasadna/open-bus-map-search/pull/434

**Comment by NoamGaash** [comment]
@amabelleS you can have this issue. the exact steps are listed in the PR description. do you have any question?

**Comment by Senior-ai** [comment]
Apologies I forgot about this task completely. Amabelle can have it, I'll take different issues in this repo soon (:

**Comment by NoamGaash** [comment]
You can also collaborate (if you want) - 
@amabelleS can try placing the map component, while you'll create a hook to retrieve the relevant data

**Comment by amabelleS** [comment]
> You can also collaborate (if you want) - @amabelleS can try placing the map component, while you'll create a hook to retrieve the relevant data

Sounds great:) I'll start working on the component part hopefully this week. Will update here/discord if I have any questions.

**Comment by amabelleS** [comment]
I think @itai-rozen is working on this issue now, pr #434

**Comment by amabelleS** [comment]
> @amabelleS you can have this issue. the exact steps are listed in the PR description. do you have any question?

Is @itai-rozen working on this issue now? pr #434 
I'm not sure if to start working on it or not. Got delayed on another project so I did not start yet...

**Comment by NoamGaash** [comment]
I believe it's save to assume no one is working on this right now.

**Comment by amabelleS** [comment]
> I believe it's fair to assume no one is working on this right now.

If I'm correct, #434 is adding a map for planned routes - that is rides in the future.
This issue is for adding a map for the last ride of a given line.
?

It's confusing because their title is the same. Is #434 for the single-line map page?
Is there a link now to the profile page, how is it connected to the flow / UX?

**Comment by NoamGaash** [comment]
@amabelleS 
No, my bad, I didn't notice there are new commits in @itai-rozen 's PR.
Seems like Itai made a progress last week.
Would you like to help reviewing his code?
Apologies for the misunderstanding

**Comment by amabelleS** [comment]
> @amabelleS No, my bad, I didn't notice there are new commits in @itai-rozen 's PR. Seems like Itai made a progress last week. Would you like to help reviewing his code? Apologies for the misunderstanding

All is good:) there are a lot of other issues to pick, and I would love to help with the review. I think he is currently still working on it, making the changes you requested, from what I understand from your chat in the PR.

**Comment by amabelleS** [comment]
> > @amabelleS No, my bad, I didn't notice there are new commits in @itai-rozen 's PR. Seems like Itai made a progress last week. Would you like to help reviewing his code? Apologies for the misunderstanding
> 
> All is good:) there are a lot of other issues to pick, and I would love to help with the review. I think he is currently still working on it, making the changes you requested, from what I understand from your chat in the PR.

Update:) I looked at the files changed in the PR, and I got confused:) but now I think I figured it out.
#318 is also about adding the map component from single-line map page to the profile page.
@itai-rozen is working on adding the stops and the line to the map component - what I saw in the PR is that the file changes are only to the single line page, not the profile page. I do not know if we even had an open issue for that, but it seems right:)

So I think we should wait to see if we have a hook ready, @Senior-ai is working on it if I'm correct. And then we can implement a call to the last stops in the profile page, rendering the same map from the single-line map page.

**Comment by itai-rozen** [comment]
Hey guys! sorry i was a bit tied up with other things
basically i added the original route with its defined stops to the map, along with the actual route with its recorded stops.
I want to add an index at the corner of the map that shows which is which, and i want the map to be auto-focused on the route once route is loaded.
If any clarifications needed regarding the code ive written so far i'd be happy to clarify:)
akhla yom

**Comment by NoamGaash** [comment]
@itai-rozen could you please link the relevant PR?

**Comment by NoamGaash** [comment]
@itai-rozen did a great job implementing a map that contains both planned and actual route
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/3b9b2c27-cb3c-46c9-a6a3-9bca42bf149f)
Yet, there are few problems:
1. We don't have this map in the profile page
2. We have different icon for the first point and the rest of the points (why?)
3. We don't always see the planned rout (why?)
I'll open three issues for these problems
Thanks everyone

**Comment by itai-rozen** [comment]
about 2 - i did this on purpose, it seemed a little busy and i thought it
might delay the render, gonna fix it in a new branch

‫בתאריך שבת, 2 במרץ 2024 ב-12:50 מאת ‪Noam Gaash‬‏ <‪
***@***.***‬‏>:‬

**Comment by itai-rozen** [comment]
but i dont see an issue for this, @NoamGaash i think you made 2 duplicate issues

**Comment by NoamGaash** [comment]
@itai-rozen I didn't made an issue for the second task, but the issues I've made aren't duplicated. One is for displaying formatted data about the line, and one is about bringing the maps
