### ISSUE TITLE
place a copy of `single-line-map` (מפה לפי קו) inside the line profile page

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#318]
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/ee405fc4-f954-42ac-81c9-d9c4bd888f31)
Add a widget to the profile page with a "start time" picker, that will show a map of the selected actual ride

**Comment by NoamGaash** [comment]
see #193 for more ideas

**Comment by i5x64BIT** [comment]
Can you clarify the issue? how do I get to this profile page?

**Comment by NoamGaash** [comment]
the address https://open-bus-map-search.hasadna.org.il/profile/124314 should lead to the profile page. However, seems the entire page should be fixed first

**Comment by amabelleS** [comment]
This is a sub-task of #316.
I think we should develop a hook to retrieve the last stops of that line, we also discussed it lately in the discord group:)
In PR #434 itai is adding stops as a param to the map component in the single line map page. Then we can use the same map component to display the stops on a map on the profile page
Is there an open issue for the hook part?

**Comment by NoamGaash** [comment]
@amabelleS it's not a sub-task. I want two maps - one for the last planned ride, other for the last executed ride

**Comment by amabelleS** [comment]
> @amabelleS it's not a sub-task. I want two maps - one for the last planned ride, other for the last executed ride the hook is implementation detail, not a requirement specification. we don't need issue for that

Thank you for explaining this to me:) I'm still trying to understand - this issue is about adding a copy of the single line map in the profile page = for the last executed ride of that line. 
#316 is adding a map (the same map component, or similar) to the profile page, but for the planned last ride. 
Is it the same ride, but the difference is between planned/supposed stops and a line between them, and actual/executed ride?

Maybe we need a Figma for the profile page, it will be easier for the developers, and for sure will look better.

**Comment by NoamGaash** [comment]
this issue is for adding the entire page, including the date-time pickers, excluding the bus-lines picker. fill free to create a figma / zeplin / xd if you think it will help

**Comment by itsoriki** [comment]
@NoamGaash I am a bit confused - I merged my #744 but going to https://open-bus-map-search.hasadna.org.il/profile/4184905 still shows the old style. I saw that the pipeline was successful. What am I missing here? Aren't the changes automatically deployed?

**Comment by itsoriki** [comment]
Should be resolved by #744 but I am not closing yet as I didn't see the new design in production somehow

**Comment by NoamGaash** [comment]
sometimes the production takes some time to update

**Comment by itsoriki** [comment]
This issue has been resolved by #744

**Comment by NoamGaash** [comment]
Thank you @itsoriki !
@all-contributors please add @itsoriki for code
:medal_sports:
