### ISSUE TITLE
add busses logos

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#32]
[bus logos.zip](https://github.com/hasadna/open-bus-map-search/files/12519707/bus.logos.zip)
replace the icons on the map to better icons
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/971f3cdf-91da-4116-b33e-6fdad8237976)

לכל נקודה על המפה יש attribute בשם operator_id. אגד למשל עם id=3 לכן התמונה היא 3.svg

**Comment by rzarviv** [comment]
Hi Noam, could you please assign me to this task?
Thanks!

**Comment by NoamGaash** [comment]
sure! good luck
I'm here for any question :)

**Comment by ShayAdler** [comment]
@rzarviv you can take a look at the [figma](https://www.figma.com/file/NL8EgYn28UPTaZOPPMafpP/Untitled?type=design&node-id=0-1&mode=design&t=PQsFMlMLbeMlek0X-0) for the bigger picture :)

**Comment by NoamGaash** [comment]
[bus logos (1).zip](https://github.com/hasadna/open-bus-map-search/files/12579054/bus.logos.1.zip)
[logos.zip](https://github.com/hasadna/open-bus-map-search/files/12579056/logos.zip)
new files :)

**Comment by rzarviv** [comment]
Thanks @NoamGaash and @ShayAdler , I'll update the bus logos.
By the way, do you want to keep the existing design of `colorIcon` (with the rotation and the background-color)? in my opinion, the `background-color` may conceal the bus logo and make it difficult for the user to identify the bus operator.

**Comment by rzarviv** [comment]
> [bus logos (1).zip](https://github.com/hasadna/open-bus-map-search/files/12579054/bus.logos.1.zip) [logos.zip](https://github.com/hasadna/open-bus-map-search/files/12579056/logos.zip) new files :)

@NoamGaash what's the difference between the two `.zip` files (and which of them to use)?

**Comment by NoamGaash** [comment]
@rzarviv one file contains the busses:
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/fc687b6e-a8b9-49a9-aae8-e68104662caa)
the other contains the logos:
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/8746a17f-293e-445c-9593-d68c773ce7a6)

- The logos are good for things like charts,
- The bus icons are great for maps
I believe the rotation can be omitted, and white circle can be added in the background, but feel free to be more creative.

Dana made a beautifull following suggestion (in the Figma file)
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/c77091b4-4e1e-4cd8-96fc-d2a22183248c)
