### ISSUE TITLE
Support locale direction

### ISSUE THREAD

**Issue by yardenmezi** [hasadna/open-bus-map-search#331]
It is better if the direction (rtl/ltr) fits the language.
Current situation:
- The app is RTL by default
- There is a locale translation, but the direction is still RTL when switching to English.

may be can be solved by using the React locale library 
(To switch web to English type "english")

Example (Current/Desired)
<img width="646" alt="Screen Shot 2023-12-19 at 3 46 01 PM" src="https://github.com/hasadna/open-bus-map-search/assets/58609921/2c7b2c80-15d9-43b0-b09f-25f539dd72bf">
<img width="643" alt="Screen Shot 2023-12-19 at 3 45 42 PM" src="https://github.com/hasadna/open-bus-map-search/assets/58609921/8efc4b6f-5572-4c94-9bce-b61a5bab298a">

**Comment by amabelleS** [comment]
I tried to check this. To change to English translation I imported 'antd/es/locale/en_US', then called it here: 
<img width="286" alt="image" src="https://github.com/hasadna/open-bus-map-search/assets/45571546/a31ffb04-6520-472d-ab83-05f76eadb544">

But all the pages remained in Hebrew. So I'm missing something. 
I also think that when we implement the translation switch there will be other modifications to make accordingly in all the pages.
