### ISSUE TITLE
Unknown in קיום נסיעות component

### ISSUE THREAD

**Issue by UrielOfir** [hasadna/open-bus-map-search#339]
![Screenshot from 2023-12-25 09-28-12](https://github.com/hasadna/open-bus-map-search/assets/30144878/3bdcde5f-ed98-4044-8ea5-7a581a7861ee)

**Comment by amabelleS** [comment]
I'll take this one, probably related to the translations module..

**Comment by amabelleS** [comment]
בגרסא שכרגע אצלי הטולטיפ לא עובד.. 
<img width="197" alt="image" src="https://github.com/hasadna/open-bus-map-search/assets/45571546/75d6d319-c287-4f05-a3c2-b8ad14ca4993">

**Comment by amabelleS** [comment]
זה קורה כי זה המידע שמגיע מהשרת, צריך לתייג את הבעיה לback-end אם אני לא טועה. אולי לסנן אובייקטים כאלו לפני השליחה:

<img width="420" alt="image" src="https://github.com/hasadna/open-bus-map-search/assets/45571546/8fa625d4-1639-4532-aa41-db069f49dbb5">

**Comment by IdanDover** [comment]
maybe we can remove it from the frontend for now until they resolve it in the backend
