### ISSUE TITLE
remove extra empty space at the page top

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#345]
currently the situation is that some pages has empty space at the top
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/d6f9a24a-41b6-4f0f-8885-9b7f8246f970)
which should better to be reduced

**Comment by BinaHovav** [comment]
Hey, I'll do that :)

**Comment by NoamGaash** [comment]
solved,
thanks @BinaHovav !

**Comment by BinaHovav** [comment]
sure :)
