### ISSUE TITLE
change dark mode background-color

### ISSUE THREAD

**Issue by Roni750** [hasadna/open-bus-map-search#356]
I think that having pure black (#000) as background color, looks a bit rough in contrast to the text color.
There are many alternatives that would look better, you can check out some of them [right here](https://domainsandchampagne.com/alternatives-to-true-black-for-your-color-palette/).

![image](https://github.com/hasadna/open-bus-map-search/assets/104915367/2e003573-1f10-4fcb-b9f4-33846d9d8f87)

**Comment by brachaer** [comment]
אשמח לקחת על עצמי את הissue

**Comment by Roni750** [comment]
> אשמח לקחת על עצמי את הissue

רשמתי אותך על ה-issue, בהצלחה (:

**Comment by brachaer** [comment]
אני כרגע משחררת את הissue לא רוצה לתפוס אותו יותר מידי זמן.

**Comment by IdanDover** [comment]
I can take this one on

**Comment by NoamGaash** [comment]
thanks @IdanDover !
