### ISSUE TITLE
fix the look of `נסיעות שלא יצאו` page

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#367]
currently the title is missing, and top input caption is half hidden:
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/3d5aec14-b597-4053-97e4-beeade62d77f)
we need to have a title at top of the page, and may be also the description of - what exactly user can see here

**Comment by BinaHovav** [comment]
hey i'll do that :)
