### ISSUE TITLE
dashboard widgets have no `gap` between then

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#375]
widgets have no `gap` between themselthes
also the have inner border
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/80469261-feb0-44cf-a78c-711e4f6bd633)
here is a look it has before:
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/38adbb7a-7752-4e73-a052-ba1bdcb1da21)

**Comment by brachaer** [comment]
אני אנסה לפתור את זה :)

**Comment by NoamGaash** [comment]
solved by @brachaer 
thank you!
