### ISSUE TITLE
Bug: add debounce when searching the route directions

### ISSUE THREAD

**Issue by ShayAdler** [hasadna/open-bus-map-search#38]
When searching for the route directions here, and typing "64" fast enough, I get the results of line "6" instead of "64":

Expected:
<img width="858" alt="image" src="https://github.com/hasadna/open-bus-map-search/assets/61648359/438a2fd1-e734-4c76-b945-fdcbbe1aeab8">

Actual:
<img width="847" alt="image" src="https://github.com/hasadna/open-bus-map-search/assets/61648359/5f0f7c70-4fa2-4e00-8706-8b6965f6cd1a">

**Comment by ArkadiK94** [comment]
Assign me pls

**Comment by NoamGaash** [comment]
thanks @ArkadiK94 ! :crown:
