### ISSUE TITLE
Dark mode switches off when the page reloads

### ISSUE THREAD

**Issue by oribro** [hasadna/open-bus-map-search#383]
When the user reloads (refresh) the page, dark mode is gone.
I think it should stay on as long as the user didn't explicitly switched it off.
What do you guys think? I can take this one.
Thanks! 💯

**Comment by NoamGaash** [comment]
sounds great. you can use `useLocalStorage` or something similar

**Comment by echelonnought** [comment]
Hi @NoamGaash, wanted to find out if this has been fixed already?
Would like to work on it. Thank you!

**Comment by NoamGaash** [comment]
not yet, the issue is still open. go ahead! good luck and welcome :smile: :rocket:

**Comment by echelonnought** [comment]
Hey @NoamGaash, I just opened a pull request to this with a fix to it. If it hasn't been fixed yet, it'd be great to take a look at it!
Thanks!

**Comment by oribro** [comment]
Thanks @echelonnought, I didn't have time to work on this so you can have this one 👍
