### ISSUE TITLE
Add right navbar on Figma

### ISSUE THREAD

**Issue by BinaHovav** [hasadna/open-bus-map-search#386]
https://www.figma.com/file/0D6JxNw691wIstb0wuR5NW/DataBus-Design?type=design&node-id=0%3A1&mode=design&t=Vn5n2YvKCKIu3WyG-1

<img width="188" alt="image" src="https://github.com/hasadna/open-bus-map-search/assets/123931280/407003c0-92ba-4eb4-a5da-da8266c19d0e">

Currently the navbar is a copy-paste screenshot, need to add and design it properly.

**Comment by mktana** [comment]
!assign

**Comment by NoamGaash** [comment]
@BinaHovav I see you've added `CSS` and `frontend` issue, but it seems like the right label should be `no-code`. Let me know if I'm mistaken

**Comment by BinaHovav** [comment]
yes you're right @NoamGaash

**Comment by NoamGaash** [comment]
irrelevant - I don't see anyone using figma.
