### ISSUE TITLE
Better inputs design

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#39]
* fix direction (text direction should be RTL, alignment to right, buttons should be to the left)
* fix placement - align all inputs to the same column

![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/eb73299e-bfb6-491a-9741-ab58cbb1db6e)

**Comment by aviv1620** [comment]
Assignees

**Comment by aviv1620** [comment]
![Untitled](https://github.com/hasadna/open-bus-map-search/assets/44925669/e2957251-370d-459f-b70c-b8ff681bd6e8)
I fix the direction. Tomorrow I will fix the placement in another PR.
the WARNING `Failed to parse source` it in create-react-app.
have PR in create-react-app that still open https://github.com/facebook/create-react-app/pull/11752
The last mention came last week.

**Comment by NoamGaash** [comment]
@aviv1620 thanks! I'll take a look
anyway, specifically CRA is no longer maintained (see their commit history)

**Comment by aviv1620** [comment]
I use MUI grid v2 for the layout.
https://mui.com/material-ui/react-grid2/

look much better.
on desktop and also on mobile(bonus)
![desktop](https://github.com/hasadna/open-bus-map-search/assets/44925669/5662cae3-93a6-4b68-96de-4ef30d3dadc2)
![mobile](https://github.com/hasadna/open-bus-map-search/assets/44925669/6a5bc6db-e492-4d88-800c-6e60671c9f21)

**Comment by NoamGaash** [comment]
I think it's much better now.
Feel free to re-open this issue with concrete examples of how can we improve
