### ISSUE TITLE
make the logo white on dark mode

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#394]
Nice issue for junior first-time contributors
the logo should be white on dark mode
(use css `fill` and `stroke`)
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/b1e3dbd9-803c-4930-81f5-852eb9d87d69)
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/4d1506df-dcef-427d-9167-4de7d21f00ce)

**Comment by isaiahthedev** [comment]
Hi @NoamGaash, it's my first day trying to contribute. I hope that I did everything correctly!
