### ISSUE TITLE
Move `colorIcon` To a Separate File

### ISSUE THREAD

**Issue by rzarviv** [hasadna/open-bus-map-search#40]
The `colorIcon` function is defined in two files (`RealTimeMapPage` and `BusLayer`) and have the same functionality and style.
Do you want to keep it as is or to move it to a separate file?

**Comment by NoamGaash** [comment]
sounds great!
moving it to `util` file/folder will make sense

**Comment by keshet1** [comment]
Hey guys!
I moved the function to another file under utils just like @rzarviv suggested and renamed it to `busIcon` as it made more sense.
I don't have permission to push the branch, can you help me?

**Comment by rzarviv** [comment]
Hi @keshet1, in order to contribute to this repo, you need to follow these steps:

1. Fork this repo. 
2. Create a branch in your fork and make your changes in it.
3. Create a Pull Request and assign one (or more) of the project maintainers to review your code.

If you encounter any problem with any of those steps, please comment here and we'll try to help.

**Comment by keshet1** [comment]
> Hi @keshet1, in order to contribute to this repo, you need to follow these steps:
> 
> 1. Fork this repo.
> 2. Create a branch in your fork and make your changes in it.
> 3. Create a Pull Request and assign one (or more) of the project maintainers to review your code.
> 
> If you encounter any problem with any of those steps, please comment here and we'll try to help.

Did these, but it seems I cannot assign anyone for reviewing

**Comment by rzarviv** [comment]
I don't know why you weren't able to ask for a review (maybe it's a permission issue), but I assigned @NoamGaash and myself to review your changes.

Thanks for your contribution, @guyStrauss!
