### ISSUE TITLE
חברה מפעילה input inconsistency

### ISSUE THREAD

**Issue by i5x64BIT** [hasadna/open-bus-map-search#401]
The fact that items are pre-selected creates inconsistensies between pages and does not reflect the db.
I would suggest to chnage the behavior of the component to fetch the db instead.

To make it faster I would say to cache the data from the landing page (קיום נסיעות) charts and use them as the options, but this is out of the scope of this issue.

<img width="1151" alt="Screenshot 2024-01-17 at 20 01 27" src="https://github.com/hasadna/open-bus-map-search/assets/62185136/65b481ab-d3e7-4bdd-b2fb-588ba995e1d8">

<img width="410" alt="Screenshot 2024-01-17 at 20 02 14" src="https://github.com/hasadna/open-bus-map-search/assets/62185136/cc633305-cd95-4389-ab01-6766a87a68e3">

**Comment by i5x64BIT** [comment]
I want to discuss possible solutions, should I do it here or on slack?
After clarification you can assign me to this one!

**Comment by NoamGaash** [comment]
@i5x64BIT could you please clarify and provide example for inconsistencies / false information?
This is the perfect place for discussing possible solutions for this issue

**Comment by i5x64BIT** [comment]
https://github.com/hasadna/open-bus-map-search/assets/62185136/391d741e-7952-463f-a676-b83caddc812d

So I found out that this issue is because instead of showing all the operators, we show only the major and pass the filtered as the options to Autocomplete.

**Comment by i5x64BIT** [comment]
BTW the data for `OperatorSelector` is beign pulled from the API, so all the inconsistencies arrise from the filtering.
In my opinion having the exact same input field display different ammounts of data over the app is not a good UX, getting everything and scrolling through is much better in my opinion.

**Comment by i5x64BIT** [comment]
https://github.com/hasadna/open-bus-map-search/assets/62185136/a1f98fe1-1318-4f7e-aadc-264860070d89

A followup on this issue is some wierdness with WorstLinesChart, where operators that aren't included in `RELEVENT` are not displayed properly.

**Comment by NoamGaash** [comment]
@all-contributors please add @Haswell-s for code
