### ISSUE TITLE
Incorrect scrollbar styling when swapping to dark mode

### ISSUE THREAD

**Issue by R894** [hasadna/open-bus-map-search#415]
### Steps to Reproduce
1. Navigate to the website
2. Swap to dark mode

### Expected Behavior
- The scrollbar styling should swap to dark mode.

### Actual Behavior
- The scrollbar styling remains light.

### Affected Environments
- **Browsers:**
  - Chrome
  - Edge

### Screenshots

![image](https://github.com/hasadna/open-bus-map-search/assets/54629307/1ab60ca7-0dfd-43e6-af63-2773c63abcea)

**Comment by YahavSofer** [comment]
I would like to take it on me please
