### ISSUE TITLE
Single Line page - Date label is partially hidden

### ISSUE THREAD

**Issue by R894** [hasadna/open-bus-map-search#417]
### Steps to Reproduce
1. Navigate to the website
2. Click on "מפה לפי קו"

### Expected Behavior
- The date label fully displays

### Actual Behavior
- The date label is partially hidden

![image](https://img001.prntscr.com/file/img001/d66nyXfzRtSPabi97BHvYw.png)

**Comment by shootermv** [comment]
can i take this issue?

**Comment by R894** [comment]
This issue has been fixed in pull request #420 . Closing the issue.
