### ISSUE TITLE
Implement homepage design according to figma

### ISSUE THREAD

**Issue by BinaHovav** [hasadna/open-bus-map-search#421]
The basic files and structure is in the project, now the need is to design it according to figma design.
In order to see the page on localhost, change the end of the path to 'home'.

Link to Figma design (still needs improvement but this is the basic) :
https://www.figma.com/file/0D6JxNw691wIstb0wuR5NW/DataBus-Design?type=design&mode=design&t=TtyNCSU8UuBthoOY-0

**Comment by amabelleS** [comment]
Correct me if I'm wrong.  The "לתרומות" in the side nav is supposed to be at the bottom of the screen, as the green footer.
 The main content of the home page is supposed to be scrollable.

**Comment by itsoriki** [comment]
@amabelleS Hi, how is the mission going so far? Do you need any help?

**Comment by NoamGaash** [comment]
@amabelleS let us know where are you standing and if you need any help! If you're still on this issue, please let us know and you'll be re-assigned
Thanks!

**Comment by itsoriki** [comment]
Progress:

![image](https://github.com/hasadna/open-bus-map-search/assets/93577239/0afca1dc-5850-4fb7-9e69-fe10085c5947)
