### ISSUE TITLE
Suggestion: donations page in a new tab / add some text before link

### ISSUE THREAD

**Issue by yardenmezi** [hasadna/open-bus-map-search#422]
Current situation: when someone clicks "לתרומות", it leads to another page (and exits the open-bus site)
The problem is that it looks to the user like it leads to another page and is unexpected.

My suggestion is to add some text (something like "כדי לעזור לנו להמשיך לקיים את הסדנה לידע ציבורי, ניתן לתרום לנו באמצעות jgive")
Another option is to open the link in another tab (but I like option 1 best because it lets the user know exactly where it goes).

What do you guys think? (I always click there by mistake so I thought that might be the user experience)

**Comment by xoRmalka** [comment]
I discussed this with @NoamGaash  last week, I will take care of it :)

Regarding the text that explains, I think it's too long for a menu, and setting up a dedicated page for that seems a bit unnecessary to me, doesn't it?

**Comment by yardenmezi** [comment]
Great! :)
I agree it's too long for a menu, and I can see why it seems a little overkill to have a dedicated page (if no additional content). My thought was to have a unified structure of menu -> page, But having a new tab, or any idea that will make the flow more comfortable can work.

**Comment by NoamGaash** [comment]
maybe JGive can be embedded somehow?
https://jgivesupport.zendesk.com/hc/he/articles/4408727702930-%D7%9B%D7%99%D7%A6%D7%93-%D7%9E%D7%98%D7%9E%D7%99%D7%A2%D7%99%D7%9D-%D7%97%D7%9C%D7%95%D7%9F-%D7%AA%D7%A8%D7%95%D7%9E%D7%94-%D7%97%D7%9B%D7%9D-%D7%91%D7%90%D7%AA%D7%A8-%D7%94%D7%A2%D7%9E%D7%95%D7%AA%D7%94-

**Comment by xoRmalka** [comment]
Yes, this is an excellent option, this way the user does not exit the application.

@NoamGaash, I would appreciate it if you could check with whoever is responsible on behalf of the association, for producing the iframe tags.

**Comment by shootermv** [comment]
i have two suggestions on this issue which i wish to put for a consideration:
1. we can move `dontations` link to the topbar (where is also github external link )
2. we can display a modal (on menu item click) with donations page of jgive embedded

**Comment by NoamGaash** [comment]
see this widjet:
https://www.hasadna.org.il/
it's just an `img` with a link
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/bdb450ed-07b2-4f3d-a750-d25e8c341f21)
we can use it this way for now

**Comment by xoRmalka** [comment]
I think it is unnecessary to create a model/page to display a non-functional image and redirect to an off-site page.

For now, I think the solution is that it will remain in the menu, only that it will open in another tab.

**Comment by NoamGaash** [comment]
@xoRmalka let us know where are you standing and if you need any help! If you're still on this issue, please let us know and you'll be re-assigned
Thanks!

**Comment by xoRmalka** [comment]
@NoamGaash 
I'm waiting for the IFRAME tag for the completion.

can you try to generate it according to this tutorial:
https://jgivesupport.zendesk.com/hc/he/articles/4408727702930-%D7%9B%D7%99%D7%A6%D7%93-%D7%9E%D7%98%D7%9E%D7%99%D7%A2%D7%99%D7%9D-%D7%97%D7%9C%D7%95%D7%9F-%D7%AA%D7%A8%D7%95%D7%9E%D7%94-%D7%97%D7%9B%D7%9D-%D7%91%D7%90%D7%AA%D7%A8-%D7%94%D7%A2%D7%9E%D7%95%D7%AA%D7%94

**Comment by NoamGaash** [comment]
Hi @xoRmalka , we've asked JGive to enable this feature for us, but their pricing was too expensive for us so unfortunately we won't be able to use it

**Comment by supervxn** [comment]
@xoRmalka Nice to meet you and work on the same project.

**Comment by supervxn** [comment]
@xoRmalka nice to see you in this issue also :-)

**Comment by xoRmalka** [comment]
Hi @NoamGaash, I just made a PR for this issue:
https://github.com/hasadna/open-bus-map-search/pull/833

**Comment by xoRmalka** [comment]
Solved!
