### ISSUE TITLE
Databus logo out of alignment in English mode

### ISSUE THREAD

**Issue by R894** [hasadna/open-bus-map-search#425]
### Steps to Reproduce
1. Navigate to the website
2. Type "english"
3. Click on the newly appeared "Change Language" button in the menu

### Expected Behavior
- The Databus logo is in correct alignment

### Actual Behavior
- The Databus logo is out of alignment

### Screenshots
![image](https://github.com/hasadna/open-bus-map-search/assets/54629307/e5c2dd2f-c091-4c46-bb49-ef1cb5787013)

**Comment by NatalieShamir** [comment]
Hey there, I am willing and able to take this one- please assign me :)

**Comment by itsoriki** [comment]
@NatalieShamir Hi, how is the mission going? Need any help?

**Comment by dorinzrihen** [comment]
Can i take this one?

**Comment by itsoriki** [comment]
Sure! Just notice that in Hebrew the alignment shouldn't change...
