### ISSUE TITLE
Unable to run project locally

### ISSUE THREAD

**Issue by IdanDover** [hasadna/open-bus-map-search#428]
**Steps to Reproduce**

1. clone repository
2. run npm install in terminal
3. run npm start

It throws the following error:
![Screenshot 2024-01-23 110703](https://github.com/hasadna/open-bus-map-search/assets/111203178/f0b52df4-9d75-40bf-8c81-be023838a32c)

My system and node specs:
node v18.16.0
typescript v5.1.3
Windows 11 Pro

**Comment by IdanDover** [comment]
I was able to run it locally only when I added this devDependencies:

1. @swc/cli
2. @swc/core

Please tell me if it's fine to add those dependencies to the project

**Comment by NoamGaash** [comment]
could you please create a pull request with the suggested changes? let's see how the CI is handling that
