### ISSUE TITLE
make e2e tests faster using har files

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#454]
first problem: e2e tests are slow because they send real queries to the backend
second problem: #435 

solution: use HAR files to capture backend responses

example: https://github.com/hasadna/open-bus-map-search/blob/5cad578b5f8a4cb9c697cd45f21ecea3af7a3b8e/tests/dashboard.spec.ts#L6

**Comment by R894** [comment]
Hi,
I'm interested in working on this issue, could you please assign it to me?

**Comment by NoamGaash** [comment]
sure, thanks! @R894 :1st_place_medal:
