### ISSUE TITLE
Fix Input Misalignment in the "SingleLineMapPage" Page

### ISSUE THREAD

**Issue by Mordechai1323** [hasadna/open-bus-map-search#51]
![image](https://github.com/hasadna/open-bus-map-search/assets/112948082/917c62d0-5ad6-4460-b31b-161dc8bb3ecb)

**Comment by ArkadiK94** [comment]
This was fixed in issue #39 so I am closing this issue for now. @NoamGaash

**Comment by NoamGaash** [comment]
@ArkadiK94 thank you!
