### ISSUE TITLE
Visualize data about a bus-line

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#543]
# Where is it?
1. go here:
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/0f35ec7d-f77f-4315-a6cd-d5ed22b5c155)
2. go back in time :timer_clock: 
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/1ffa8353-7353-48de-bf7d-6ddf458554f6)
3. click a bus:
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/d23d3be3-41bd-47f8-82f6-0e08cc8974c5)
4. click the line title:
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/6d581a9e-a772-4892-9f48-c2a2bc8834b2)

# The problem
It's an ugly, unfinished page

# What could you do?
Help us!
take the data (yes, the JSON thing) and make it look like something that a real user can actually read and understand

**Comment by Darkmift** [comment]
I might want to pitch in on this.

**Comment by NoamGaash** [comment]
@Darkmift sure!
Feel free to add things
@Tamir198 please let each other know what you're doing, to prevent editorial conflicts

**Comment by Darkmift** [comment]
just saw @Tamir198 work on #557 
I will discuss with him how to promote this.

**Comment by itsoriki** [comment]
@NoamGaash The PRs of Tamir didn't resolve this issue?  What's the status now?

**Comment by NoamGaash** [comment]
@itsoriki 
Tamir's work is an excellent start, but it's still a little ugly (no offence), and unfinished page. There's a lot of work to be done.

**Comment by Tamir198** [comment]
Ye I agree with noam , more work to be done on this page

**Comment by NoamGaash** [comment]
examples -

- [ ] translate all texts
- [ ] extract data from fields (route long name contains both start and end points)
- [ ] use the API to convert IDs and MKTs (מק"טים) to a real data
- [ ] make the map work ([here](https://open-bus-map-search.hasadna.org.il/profile/4477283) it doesn't)
- [ ] remove (or fix) broken sections such as "שעות פעילות" and "הערות ועדכונים על הקו"
- [ ] improve the layout

and so on

**Comment by itsoriki** [comment]
@NoamGaash 
About the task of "make the map work" you mentioned - What should the map show exactly? (as the user just want to see a general line profile - what will work best?) What's the planned route here? What's the actual route?  What's the date range to look for (since there is no option to select the dates in the line profile page...)?

**Comment by itsoriki** [comment]
@NoamGaash 
Also, about the other task left - "use the API to convert IDs and MKTs (מק"טים) to real data" - can you be more specific about which parts of the API should be used for the conversion and how? The gtfs API? The Siri API?

Do you think we should schedule a meeting where you explain about the architecture and the backend in general for us newcomers?  Imo it would be great!!

**Comment by NoamGaash** [comment]
Sure, we can schedule and dive into the details :)
But before that - have you seen the link to the data model, and the video we have about the architecture? Chapter 8 of our youtube playlist

**Comment by itsoriki** [comment]
> Sure, we can schedule and dive into the details :) But before that - have you seen the link to the data model, and the video we have about the architecture? Chapter 8 of our youtube playlist

I did actually - definitely found a lot of useful information there, but still have some general questions

**Comment by itsoriki** [comment]
> I made a poll in Maakaf's Whatsapp group. Will Tuesday evening work for you?

Just voted! Thanks for the quick reaction :)
