### ISSUE TITLE
Add reset button to user input

### ISSUE THREAD

**Issue by ArkadiK94** [hasadna/open-bus-map-search#59]
In some pages like GapsPage and TimelinePage, I think it will be a better user experience to add a reset button. When the user would like to change the selected bus number he/she will click this button and the inputs will be removed/change to the default input. What do you think about this? @ShayAdler @NoamGaash

**Comment by NoamGaash** [comment]
I think it's a good idea - but what the default value should be? empty state isn't very useful

**Comment by ArkadiK94** [comment]
About the date, the default value will be today. Why is empty state not so useful? 🤔 I am not sure about the default values for the rest of the inputs.

**Comment by NoamGaash** [comment]
I think we shouldn't be opinionated regarding default values for fields like "operator" (מפעיל)

**Comment by ArkadiK94** [comment]
I think so as well. In my opinion, we can reset the values to empty state , and only for the date reset it to today. However,  you said that empty state is not useful. I am not sure what we should do. What do you think?

**Comment by NoamGaash** [comment]
Let's think of the problem, before jumping into solutions..
What's the use case for such a button? How does it help to the final user experience?
Did you suggested this idea because you considered a use case of a user that wants to change the operator they are searching, and feels frustration due to the need to delete the content of the input element when focused?

**Comment by ArkadiK94** [comment]
Yes, the user needs not only to change the operator but also the line number and date from the last search, so I think it is easier to remove those inputs and select/write new ones from blank.

**Comment by ArkadiK94** [comment]
Hi, I noticed something, in some input fields we have a "clear" X button in the input field , for example in "OperatorSelector" "RouteSelector" like in the image
![image](https://github.com/hasadna/open-bus-map-search/assets/76536506/7befc93c-0907-41f7-9526-b0e792cecdef)

Instead of making a separate button to reset values we can add this functionality in/beside the "LineNumberSelector" and "MinuteSelector" input fields
![image](https://github.com/hasadna/open-bus-map-search/assets/76536506/ff7eebbf-5163-4f9c-9b23-ccbcad662953)

What do you think? @NoamGaash

**Comment by NoamGaash** [comment]
I think it's a much better idea, thanks!
