### ISSUE TITLE
add youtube videos

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#605]
We have some videos describing some of the pages
https://www.youtube.com/watch?v=MJZrIxjQEH8&list=PL6Rh06rT7uiX1AQE-lm55hy-seL3idx3T

- [ ] create a youtube info component that will open a modal with a youtube video
- [ ] add this component to: 1) map pages 2) dashboard page 3) gap patterns page 4) bug report form
- [ ] link to relevant videos in out readme and contribution files

**Comment by KirilCycle** [comment]
Hello! Please can you tell more about the 'youtube info component', is it some kind of btn or link which will trigger a modal with a specific youtube video which will describe the page were it was open? I also didnt found relevant videos in readme and contribution files, can u provide link please.

**Comment by NoamGaash** [comment]
@KirilCycle Hi :)
the link to the videos playlist is the one mentioned in the issue description -
https://www.youtube.com/watch?v=MJZrIxjQEH8&list=PL6Rh06rT7uiX1AQE-lm55hy-seL3idx3T

It's up to you how to implement it, but I think that a little information icon near the page title that will open a modal with a relevant embedded video could be nice.

- dashboard, realtime map and single route map could have the "מפות וסטטיסטיקות" chapter
- the line profile page could have the "פרופיל קו" video

and so on

currently, the relevant videos are not in the readme file. adding those videos to that file is this is the third section of this task

**Comment by KirilCycle** [comment]
Hello! Thank you for the clarification, can u asing me on this issue please ?

**Comment by NoamGaash** [comment]
Sure, thank you! Welcome aboard :)
<img src="https://media4.giphy.com/media/OK914NO5d8ey9sSNAQ/giphy.gif"/>

**Comment by KirilCycle** [comment]
Hello! Can you add a permission, i tried to push and  my branch but got 403

**Comment by NoamGaash** [comment]
done :+1:
