### ISSUE TITLE
Bug - Open Menu In the Mobile Display

### ISSUE THREAD

**Issue by ArkadiK94** [hasadna/open-bus-map-search#64]
When we in mobile display of media screen less than 600px approximately and try to open the menu, it appears near the content screen and the sum of the menu width and content width is more than the actual screen so the screen slides. Better to make the menu appear above the content screen in those screen sizes.

**Comment by giladcortex** [comment]
Hi I would like to take it.

looks like you just need to add for CSS class this variables

    .main .header.open{
//new
        display: block;
        position: absolute;
        z-index: 500;
//old
        max-width: 100%;
        padding: 30px;
    }

**Comment by ArkadiK94** [comment]
@NoamGaash could you assign him?

**Comment by NoamGaash** [comment]
@giladfuchs good luck!
@ArkadiK94 thanks!
