### ISSUE TITLE
Change the title of the "realtime" page

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#685]
The term "realtime" is very confusing, as we don't have real time data. Most of the time we're able to show about 5 minutes ago.
This page is more useful for querying historical data. For example - to find out the licence plate number of the vehicle that I saw yesterday on 19:47 driving too fast in front of our local school.
Suggested new title -
* he - מפה לפי זמן
* en - Time based map

I'm open to any other suggestion

**Comment by gallaghersara** [comment]
Hey, I'll take it:)

**Comment by itsoriki** [comment]
@NoamGaash Can I take this issue?

**Comment by NoamGaash** [comment]
@itsoriki sure! go ahead! :)
