### ISSUE TITLE
Make the language button visible and visually pleasant 

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#686]
When typing "english"a new button appears:
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/4e127a60-4e53-432e-9137-afe80bfbf05b)
It's an easter egg, and we made it that way because the english mode wasn't ready to be published.
Now, it's a great time to:

- [ ] Make the button always visible (remove the Easter Egg wrapper)
- [ ] Make the button pretty

Good luck

**Comment by zushar** [comment]
Hey, I'll take it:)
thank you

**Comment by zushar** [comment]
Pull requests is  reafctor: Language toggle and en.json and he.json on cheage Language #687

**Comment by zushar** [comment]
i thought about moving it next to the icons on the top of the page and change it to the shape of a flag

**Comment by zushar** [comment]
feat: add language button #692 pr mergd
