### ISSUE TITLE
Create MapContent Component

### ISSUE THREAD

**Issue by itsoriki** [hasadna/open-bus-map-search#736]
Right now the code inside the `MapWithLocationsAndPath` component is a lot to handle + it won't let us insert our hooks to the `MapContainer` scope.

The solution here will be to **create a new component** (possibly named `MapContent`) which will contain all the JSX that is currently inside the MapContainer component (all the code in the photo attached) - enabling us write all the hooks we want

![image](https://github.com/hasadna/open-bus-map-search/assets/93577239/e7a8fcce-4aa4-42d0-9f47-b433aa235f22)

**Comment by menachem95** [comment]
Hey, I'll take it.

**Comment by itsoriki** [comment]
@menachem95 Good luck!
