### ISSUE TITLE
Duplicate donate link (dollar icon ) at the topbar

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#758]
Also ther is one more donate link at the sidebar...

**Comment by itsoriki** [comment]
See #753

**Comment by itsoriki** [comment]
@NoamGaash This issue duplicates another issue (#753)

**Comment by NoamGaash** [comment]
@itsoriki nice catch! I missed it

**Comment by NoamGaash** [comment]
Thanks both of you for paying attention for this
