### ISSUE TITLE
Get rid of CRA

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#77]
we use react-scripts, and it's deprecated
https://blog.bitsrc.io/the-future-of-react-why-create-react-app-is-deprecated-and-hooks-are-the-future-83e8a087a325

Right now, I tend to think Vite is the best alternative (if you have a different opinion, convince me)
https://dev.to/henriquejensen/migrating-from-create-react-app-to-vite-a-quick-and-easy-guide-5e72

**Comment by rzarviv** [comment]
If you don't need any Server-Side Rendering abilities then Vite is probably the best alternative for create-react-app AFAIK.

**Comment by knightcube** [comment]
I can work on this.

**Comment by NoamGaash** [comment]
@knightcube thanks! let me know if you have any question, or if there's any help required
<img src="https://media1.giphy.com/media/3oKIPnAiaMCws8nOsE/giphy.gif"/>

**Comment by knightcube** [comment]
I am following the instructions in the article that you sent. 

As per Step 8 we will have to migrate our testing library from Jest to [Vitest](https://vitest.dev/guide/). Currently, all our tests have been written in Jest. Therefore, migrating to Vitest will break the project.

I am making some changes to the `package.json` file but I am not sure what to write for `test` and `eject` as they both used react-scripts earlier.

```
"scripts": {
    "start": "vite",
    "build": "tsc && vite build",
    "serve": "vite preview",
    "test": "",
    "test:playwright": "playwright test",
    "eject": "",
    "lint": "eslint . --max-warnings 0",
    "lint:fix": "eslint . --fix",
    "format": "prettier --write './**/*.{js,jsx,ts,tsx,css,md,json}' --config ./.prettierrc"
  },
```

Thoughts?

**Comment by NoamGaash** [comment]
are you sure that we have Jest tests?

**Comment by knightcube** [comment]
@NoamGaash No we have Playwright tests.

**Comment by NoamGaash** [comment]
@knightcube Playwright won't care about the way we transpile our project. It just uses `yarn start` and looks for the `8080` port

**Comment by knightcube** [comment]
But why is the playwright test not running here? - https://github.com/hasadna/open-bus-map-search/actions/runs/6378722977/job/17313602705?pr=86

**Comment by NoamGaash** [comment]
Did you try to run it locally? Maybe its listening to the wrong port number

**Comment by knightcube** [comment]
Yeah I updated the port numbers in #86 just now.

**Comment by NoamGaash** [comment]
thank you @knightcube !
you solved a real tech debt in our project. it's super helpful and appreciated
:pray: :star: :1st_place_medal:

**Comment by knightcube** [comment]
I was calculating the impact of this contribution. 

With CRA:
Development Server Start-Up Time - 28 to 30 seconds!

With Vite:
Development Server Start-Up Time - 789 milliseconds!

MASSIVE IMPROVEMENT!
