### ISSUE TITLE
Test | header-links icons should be unique

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#775]
Test cast #1: verify that each icon inside `.header-links` is unique
This should fail:
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/780f14f8-c806-439d-ba77-f32b0f517f8e)

Test case #2: check the sidebar icons:
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/ac91d465-6fb4-46a9-a531-b39e3bc60e3a)

**Comment by dorinzrihen** [comment]
I can close this issue? Already merged a solution

**Comment by NoamGaash** [comment]
great, thanks!
