### ISSUE TITLE
Allow better zoom level

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#776]
We got this email:

חברת דן בדרום בתאריך ה14.8.2023 בשעה 22:35. הנהג הוריד את הנוסעים בגלל שמישהו עישן והנהג החליט שהוא לא מתכוון להמשיך במסלול. לאחר זמן מה שוטר אמר לנוסעים לא לעלות ונתן לנהג לנסוע לבד. בלי הנוסעים. השוטר טען כי יגיע אוטובוס חלופי . ואני שמעתי שאתם יכולים לעזור בתיעודים של האוטובוס. הקו היה 363 מאשקלון לבאר שבע. זה היה האוטובוס האחרון יצא מתחנה מרכזית אשקלון בזמן בשעה 22:00.
פונה כי הבנתי שאתם יכולים לעזור בזה.
 תודה רבה מראש!

However, when zooming to the right bus station, the data points are on top of each other and clicking the points is problematic:
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/3fb489f9-fe8f-45af-996e-f95e1e8587c2)

We should find a war to let the user inspect intersecting data points

**Comment by NoamGaash** [comment]
https://open-bus-map-search.hasadna.org.il/single-line-map?timestamp=1692005151000&operatorId=31&lineNumber=363&routeKey=%D7%AA.+%D7%9E%D7%A8%D7%9B%D7%96%D7%99%D7%AA+%D7%90%D7%A9%D7%A7%D7%9C%D7%95%D7%9F+%D7%A8%D7%A6%D7%99%D7%A4%D7%99%D7%9D%2F%D7%91%D7%99%D7%A0%D7%A2%D7%99%D7%A8%D7%95%D7%A0%D7%99-%D7%90%D7%A9%D7%A7%D7%9C%D7%95%D7%9F%3C-%3E%D7%AA.%D7%9E%D7%A8%D7%9B%D7%96%D7%99%D7%AA+%D7%91%D7%90%D7%A8+%D7%A9%D7%91%D7%A2%2F%D7%94%D7%95%D7%A8%D7%93%D7%94-%D7%91%D7%90%D7%A8+%D7%A9%D7%91%D7%A2-1%23

**Comment by dorinzrihen** [comment]
איך היית רוצה לגשת לפתרון? 
אולי להוסיף חצים ולעבור בין הנקודות לפי סדר הנסיעה?
<img width="908" alt="image" src="https://github.com/hasadna/open-bus-map-search/assets/20385035/e0a80673-cd70-4f68-8143-eaf49b56a682">


>

**Comment by NoamGaash** [comment]
זאת אפשרות.
עוד אופציות:
- הוספה של טבלה למטה
- לבדוק אם קיימת אפשרות במפה לזום יותר גבוה
- אולי להוסיף גרף מיקום לפי זמן

כנראה שיש יותר מדרך אחת לפתור את זה אבל מגניב לראות מקרה שימוש כזה ומעניין שנפתור אותו 🙂

**Comment by dorinzrihen** [comment]
I can close this issue? Already merged a solution

**Comment by NoamGaash** [comment]
Great,thanks!
