### ISSUE TITLE
new agencies should appear in the dashboard

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#789]
we should call https://open-bus-stride-api.hasadna.org.il/gtfs_agencies/list?date_from=2024-06-01 with dynamic date argument to make sure new agencies appear

**Comment by EyalIlan** [comment]
hey can i take this issue? please :)

**Comment by NoamGaash** [comment]
sure

**Comment by EyalIlan** [comment]
yay thanks :) I will start working on it

**Comment by NoamGaash** [comment]
another task (for separate pr) - add "דרך אגד" to the list of important operators

**Comment by asidelnik** [comment]
@NoamGaash 
**What does dynamic mean?**

Should date_from equal each date's current date?
Ex: today: 2024-06-11, tomorrow: 2024-06-12

Or should it equal each month's first date? (as in api url in this issue's description)
Ex: today: 2024-06-01, next month: 2024-07-01

**Comment by NoamGaash** [comment]
I think providing yesterday's date would be the safest approach, but it's up to you to decide.

**Comment by asidelnik** [comment]
@NoamGaash Can you give me push & pull request permissions?

**Comment by NoamGaash** [comment]
@asidelnik Welcome! It's great to see you here :clap:

**Comment by NoamGaash** [comment]
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/8be18684-5693-486f-9c81-d76204ecd6c2)

is it related?

**Comment by YaelChen** [comment]
@NoamGaash I thought I could test this to see that the date is dynamic, but where is this being called?
I only see yesterday's date in the END DATE of trip existence and patterns.

**Comment by NoamGaash** [comment]
@YaelChen 
https://github.com/hasadna/open-bus-map-search/blob/20b1e80509191f693cab5cb93b05268c9195e11b/src/api/agencyList.ts#L16-L24

I think that we can test few things here -
1. there's a call to a path that includes `gtfs_agencies/list`
2. the request contains a `date_from` with a recent date (let's say 0-3 days ago?)

And then we can mock the route response with some fake data - for example:
```
[{"date":"2020-02-02","operator_ref":1234,"agency_name":"להקת אווזי הבר"}]
```
to see that the new agency is reflected in the UI
