### ISSUE TITLE
DatePicker component | show invalid dates warning

### ISSUE THREAD

**Issue by ArkadiK94** [hasadna/open-bus-map-search#80]
For now, when the user selects an invalid Date, the box is marked in red.
I think it is better to add some warning in words so the user will understand why it is red...
![image](https://github.com/hasadna/open-bus-map-search/assets/76536506/404536ae-244d-46e0-b363-7ed6d911dc40)
In addition, we should make sure that if the user enters a year before X (I think make it 2000 but maybe before or after) it will be marked as well
![image](https://github.com/hasadna/open-bus-map-search/assets/76536506/f9b43bcb-f501-4779-8b6a-ef32aa8fa78a)

**Comment by ArkadiK94** [comment]
@NoamGaash @ShayAdler

**Comment by NoamGaash** [comment]
text for invalid input: "נא להזין תאריך בפורמט תקין"
the text should be aligned to the right because Hebrew is a right-to-left language.

**Comment by aviv1620** [comment]
https://mui.com/x/react-date-pickers/validation/#show-the-error

**Comment by AviadCohen24** [comment]
hi, can anyone assign this issue to me?

**Comment by ArkadiK94** [comment]
Sure, you can work on it. See the message from aviv1620.

**Comment by ArkadiK94** [comment]
I am not sure which date range to set. @NoamGaash what do you prefer?

**Comment by NoamGaash** [comment]
@AviadCohen24 it's also possible to choose the current date - we should have data up until 1-2 minute ago,

**Comment by AviadCohen24** [comment]
@NoamGaash Ok, from what date is there data documented in the API?

**Comment by NoamGaash** [comment]
I'm not sure,
you can keep it on 2010, or alternatively check the [stride API ](https://open-bus-stride-api.hasadna.org.il/docs#/siri/list__siri_rides_list_get) and sort by date descending order

**Comment by AviadCohen24** [comment]
ok.
something else, on my laptop (15.6"), the date picker container look like this:
![image](https://github.com/hasadna/open-bus-map-search/assets/47459888/ac79e067-50e3-4532-aa7b-4df5dd2e1ad1)
do you want me to take care of it and fix it in this issue or you prefer to open a new issue to take care of it?

**Comment by aviv1620** [comment]
Think open new issues.
And the place need to be here:
PR  #54 destroy the layout.
![Screenshot 2023-10-07 010101](https://github.com/hasadna/open-bus-map-search/assets/44925669/beede96e-e64d-4ad9-88cc-11c8844d1cd0)

**Comment by oribro** [comment]
@NoamGaash @ArkadiK94 
I've just uploaded a fix to this issue using @aviv1620's suggestion, and also cleaned some previous leftover error message. 
I'd appreciate your review 🥇

**Comment by aviv1620** [comment]
@oribro 
Thank you very much.
The issue it very old. and time to close it.

**Comment by NoamGaash** [comment]
@oribro great work, 10x!
