### ISSUE TITLE
home page anchor links overflows on hover, home page links cropped on mobile

### ISSUE THREAD

**Issue by yuvalkarif** [hasadna/open-bus-map-search#800]
Managed to find some css issues while playing with the site, hopefully you find these helpful.
- Anchor Overflow (.hover)
![image](https://github.com/hasadna/open-bus-map-search/assets/34835592/02e623fc-9260-437e-b8b2-45ef15828a5a)
- Actions Overflow (425px and lower)
![image](https://github.com/hasadna/open-bus-map-search/assets/34835592/5e114adb-77d4-4bad-b7fb-8a4c8034dfcb)

**Comment by yuvalkarif** [comment]
suggested minor fix (with screenshots)
#799

**Comment by asidelnik** [comment]
Another bug in homepage - when you zoom in, the footer hides the buttons.
![image](https://github.com/hasadna/open-bus-map-search/assets/10272524/d7d5d698-07b3-4fee-ac4a-707a306f1738)
