### ISSUE TITLE
Pattern tab - shows wrong data

### ISSUE THREAD

**Issue by supervxn** [hasadna/open-bus-map-search#808]
For example - the data rabge I selected is 6 days.

The data shows 2 planned trips at 5 am.

There's no way that only 2 trips are planned for 6 days.

![Screenshot 2024-06-17 125710](https://github.com/hasadna/open-bus-map-search/assets/24433493/d573de9d-f486-4aa5-a0d6-bccb60b8fa54)

**Comment by NoamGaash** [comment]
Why not? can you elaborate?
10.6 - missing ride
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/53679ee3-bdcb-4b7e-9ba4-2e68aafa1559)
11.6 - same
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/36dbd9a4-4abe-43ff-9cf5-2afc09804c39)
12.6 - Shavuot
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/4fff6728-16b2-41ca-ae1e-5130d88a0ea5)
13.6 - seems we have a problem. The line didn't work that day, but it shows false data that disappears after refresh
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/0b9d9493-e5a2-4c89-9f18-2d8c28b7bc73)
14-15.6 - weekend
16.6 - missing data

I think we should fix the description of this issue

**Comment by NoamGaash** [comment]
also, consider splitting the issue to smaller task -
1. the refresh problem is a frontend problem
2. the data integrity problem is a backend issue

**Comment by supervxn** [comment]
it's fixed :-)

I was talking about this tab:
https://open-bus-map-search.hasadna.org.il/gaps_patterns

**Comment by NoamGaash** [comment]
@supervxn both pages are using the same data. let's try to seperate problems with the data from problems with the aggregations or views
