### ISSUE TITLE
User wants to view "patterns of missed trips"

### ISSUE THREAD

**Issue by supervxn** [hasadna/open-bus-map-search#809]
![image](https://github.com/hasadna/open-bus-map-search/assets/24433493/d0a6f5c1-be43-43c2-a74f-684af7602900)

**Comment by NoamGaash** [comment]
The line (60) does not exist. Doesn't it make sense that it has no time to choose from?
What's the expected behavior?

**Comment by NoamGaash** [comment]
It says `הקו לא נמצא` - the line wasn't found.
If it's a problem, it's a missing data problem and has nothing to do with the "no options" text in the dropdown

**Comment by supervxn** [comment]
It's fixed thx. :-)
