### ISSUE TITLE
The "donations" tab in sidebar needs to open a pop up. Same as the icon in header

### ISSUE THREAD

**Issue by supervxn** [hasadna/open-bus-map-search#813]
![image](https://github.com/hasadna/open-bus-map-search/assets/24433493/e74e91da-3aeb-4376-a03c-eb7c52bc64ec)

**Comment by TomRytt** [comment]
@NoamGaash 

I think we can close this issue

**Comment by NoamGaash** [comment]
You're absolutely right, thank you 😊
