### ISSUE TITLE
Apply code review comments

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#817]
We're about to merge this PR:
https://github.com/hasadna/open-bus-map-search/pull/791

There are some minor improvements that I commented about, and I'm not sure the author of the pull request wants to fix. Never the less, he made a great feature and we want it merged.

Therefore, if anyone would like to proceed and finish up this task, it would be great. See the comments here:
https://github.com/hasadna/open-bus-map-search/pull/791

**Comment by YuvalMasada** [comment]
I'll take it if that's ok.
I saw another issue with the size of the modal and I'll fix it too. 
It needs scroll for y-axis, at least from what I've experienced.

**Comment by NoamGaash** [comment]
@YuvalMasada thank you!

**Comment by YuvalMasada** [comment]
@NoamGaash 
Hi,
I've made some local changes to this component.
I didn't change the functionality, but change the used material-ui component so dark mode will be handled automatically & and also it solves the need for adding scroll bar.
I'm adding some screenshot and if that good I'll make new branch for it.

 
![80 percent zoom  dark mode](https://github.com/user-attachments/assets/eaa9f1c5-f209-4c88-8e82-46e7314f9a51)
![80 percent zoom - light mode](https://github.com/user-attachments/assets/b688ddea-1299-48cf-b264-0293fa154a3c)
![100 percent - dark mode](https://github.com/user-attachments/assets/0016dd7f-f9e3-4a9f-b3da-83ad661ac101)

**Comment by NoamGaash** [comment]
@YuvalMasada looks great! Where can I see the code? 👏

**Comment by YuvalMasada** [comment]
@NoamGaash 
Here -> https://github.com/hasadna/open-bus-map-search/pull/852
