### ISSUE TITLE
Fix the home page

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#82]
when visiting the homepage, it should be redirected to `https://open-bus-map-search.hasadna.org.il/dashboard`.

the text "[click to navigate to dashboard.](https://open-bus-map-search.hasadna.org.il/dashboard)" should never appear

![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/e0667f02-5f60-46da-9628-4bdd68957746)

**Comment by NoamGaash** [comment]
thanks @rupeshghosh10 ! :1st_place_medal:

**Comment by rupeshghosh10** [comment]
Thanks for the review
