### ISSUE TITLE
React routing | don't include redundant URL search arguments 

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#83]
when visiting pages in the application, such as the "About" page, our routing component redirects requests such as:
https://open-bus-map-search.hasadna.org.il/about
to ugly URLs such as:
https://open-bus-map-search.hasadna.org.il/about?operatorId=&lineNumber=&routeKey=&timestamp=1696154828313

DOD:
1. distinguish pages that need those arguments from pages that don't need them
2. remove redundant arguments from URL when necessary 
3. bonus - re-attach the arguments from local storage when navigating to pages that use the search params

Good luck!
:balloon:

**Comment by ansh-saini** [comment]
Hi. I would like to work on this. Can you please assign this to me?
