### ISSUE TITLE
History tab - nothing happens when I finish selecting all fields

### ISSUE THREAD

**Issue by supervxn** [hasadna/open-bus-map-search#835]
![image](https://github.com/hasadna/open-bus-map-search/assets/24433493/e33e00bb-26f4-422b-a262-72bc55e18abb)

**Comment by TomRytt** [comment]
@NoamGaash Again, same issue as #854, would you like me to close?

**Comment by NoamGaash** [comment]
Nice catch! Thank you, let's close as duplicate :pray: :clap:
