### ISSUE TITLE
Creating a cool tooltip with bus information

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#84]
Right now, we simply dump the data that we have [here](https://open-bus-map-search.hasadna.org.il/map?operatorId=&lineNumber=&routeKey=&timestamp=1696160305698).

It is ugly.

![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/bb2b3e07-daff-44ad-bfc7-a41da35de050)

Let's make it human-readable, and show the speed, direction, and other details about this bus in a creative way.

<img src="https://media4.giphy.com/media/V1lqxDPDRfn5S/giphy.gif"/>

**Comment by LemonDrop847** [comment]
Hey! I would like to work on this, Can I be assigned?`

**Comment by knightcube** [comment]
I would like to work on this but is there any design that I can refer to? 

And also what all data should be shown from that JSON data?

**Comment by NoamGaash** [comment]
There is no design yet.
Most of the data can be found on the json that appears inside the popover.
Missing details (such as the name of the line) could be retrieved from the stride API (link to swagger exist in the readme file).
I think is can be gradually developed, seperated to multiple pull requests.

**Comment by NoamGaash** [comment]
draft (feel free to edit and improve):
https://www.figma.com/file/GeJ5S2gRgdrqTJqNzvifRV/Untitled?type=design&node-id=0%3A1&mode=design&t=C0SX9gpUjolzs143-1
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/e68e3e21-8845-4cec-aedd-dad1b5babfd5)

**Comment by knightcube** [comment]
I will complete issue #90 and then come to this. It is difficult for me to understand what all that text means as it is in a different language.

**Comment by giladfuchs** [comment]
@knightcube if you find it complicated and also you already working on another issue.

I can take this issue.
In general I think this issue is more for some Hebrew speaker.

**Comment by knightcube** [comment]
Sure @giladfuchs. Go ahead.

**Comment by giladfuchs** [comment]
@NoamGaash  can you assign me plz!

**Comment by NoamGaash** [comment]
thank you both! you're amazing :star2:

**Comment by giladfuchs** [comment]
@NoamGaash 

following this interface
blob/d856647b7a0d0ff6bf929dcea20ed25ba16c07f6/src/pages/RealtimeMapPage.tsx#L26

I can't find the bus number. 
any suggestion?

**Comment by NoamGaash** [comment]
try calling this endpoint:
https://open-bus-stride-api.hasadna.org.il/siri_rides/list?get_count=false&siri_route__line_refs=2538
