### ISSUE TITLE
card elements is hardy visible at dark mode

### ISSUE THREAD

**Issue by shootermv** [hasadna/open-bus-map-search#847]
if you look at `about` page at dark mode  - you can hardly see there are card blocks around the paragraphs...
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/984e167a-b02d-42b7-9334-80a6ea859452)
i think it can be nice if they be more visible, like here:
![image](https://github.com/hasadna/open-bus-map-search/assets/1336862/c4aaa117-cc56-48d0-90e7-2e5b1a54d39e)

**Comment by adiUngerGit** [comment]
hi, i would like to work on this issue

**Comment by TomRytt** [comment]
@NoamGaash  Can we close this?

**Comment by NoamGaash** [comment]
@TomRytt I think so, thanks!
