### ISSUE TITLE
mobile menu button accidently moved to the wrong location

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#897]
![image](https://github.com/user-attachments/assets/7942768a-0cdb-49e0-9c8f-e9cfa83ff4a1)
![image](https://github.com/user-attachments/assets/a977775c-da15-463a-a552-bd98f1a2ce79)

The menu opening botton should be spaced

**Comment by rivka14** [comment]
Hi, I’d like to contribute to this issue. Could you please assign it to me? Thanks!

**Comment by NoamGaash** [comment]
@rivka14 sure, thank you very much! welcome :)
