### ISSUE TITLE
Localization Support - Creating English Equivalent For Harcoded Texts in Texts.tsx

### ISSUE THREAD

**Issue by knightcube** [hasadna/open-bus-map-search#90]
It might be a good idea to also support English language in this app. 

I am thinking of using this library to achieve the same - https://www.npmjs.com/package/react-localization

**Comment by NoamGaash** [comment]
It's a great idea!
But let's use something a little more popular
How about i18n?
![image](https://github.com/hasadna/open-bus-map-search/assets/11145132/f94bbd2c-c8e0-4fc4-9b9d-3957cc54bf99)
(it's just a suggestion, please share if you have thoughts about why react-localization is better for our project. I don't know enough about this library)

**Comment by knightcube** [comment]
I agree with you. After doing a bit of research, I do feel i18n is more popular. 

I can get started on this. 

Kindly assign it to me.

**Comment by knightcube** [comment]
I would also like to know what is the current user base. Can it only be used by people who understand Hebrew?

I just want to see how impactful will adding English support be. 

Will there be any potential improvement in any product or business metric?🤔

**Comment by NoamGaash** [comment]
Despite the official languages of Israel are Hebrew and Arabic, English is widely used.
The primary user base for OpenBus is the Israeli audience. This project tracks Israeli public transportation, and we try to investigate problems and how can it be improved,
In the future, I thing Hebrew, English and Arabic should be supported

**Comment by NoamGaash** [comment]
I believe this ticket can be closed, as we now have both `i18n` installed and most of the texts are translated.
We can open dedicated issue for specific translations that are missing
Thank you very much @knightcube for your activity in the project it's very appreciated :pray:
