### ISSUE TITLE
fix: Donation modal text should be white in dark mode

### ISSUE THREAD

**Issue by YaelChen** [hasadna/open-bus-map-search#910]
The Text color in the Donation modal isn't changing to white in dark mode.
In the meanwhile I've colored it blue so it can be visible in both dark and light modes,
but it needs to be fixed properly.

When fixing, the blue text style need to be deleted from DonateMoodal.tsx (line 27: "style={{ color: '#1498e5' }}")

**Comment by LeoBonjo** [comment]
Hello, I would like to work on this issue. May I have write permissions to this repo?

**Comment by NoamGaash** [comment]
Thank you very much!
closed by https://github.com/hasadna/open-bus-map-search/pull/920
@all-contributors please add @LeoBonjo to code
Congrats for merging your first PR in DataBus!
<img src="https://media1.giphy.com/media/oRFdoOGBqFikXk8PXh/giphy.gif"/>
