### ISSUE TITLE
Adding the list of stops in the line profile page

### ISSUE THREAD

**Issue by Tami-Co** [hasadna/open-bus-map-search#916]
@NoamGaash 
I have completed the task, and the stations have been added, as shown in the image.
Could you please approve me to push the changes?

before:

![376544839-e8e094bb-e018-4992-8f8d-78dd75c1af13](https://github.com/user-attachments/assets/78f0484d-f954-4ae6-b2b1-5a00017a16ea)

after:

![image](https://github.com/user-attachments/assets/f14770cb-535e-4248-8e24-39074f6790a1)

**Comment by NoamGaash** [comment]
Hi @Tami-Co ! Thanks!
I think I have invited you, could you please verify that it worked?
Great to see this screenshot! Looking forward to see the pull request :blush: 

<img src="https://media1.giphy.com/media/7eAvzJ0SBBzHy/giphy.gif"/>
