### ISSUE TITLE
css | fix donation modal for mobile devices

### ISSUE THREAD

**Issue by NoamGaash** [hasadna/open-bus-map-search#942]
this is how it looks today:
![image](https://github.com/user-attachments/assets/ca64aebb-a81c-4813-836c-e496fd63929c)

**Comment by rivka14** [comment]
Hi, I’d like to work on this issue. Could you please assign it to me?

**Comment by NoamGaash** [comment]
Hi @rivka14 ! Thanks!
Have you seen the #945 pull request that @yontank submitted? Just making sure we won't have collisions.

**Comment by NoamGaash** [comment]
Solved in #945 . Thanks @yontank !
